In [1]:
import pandas as pd
productgroupset_map = {
    '灶具':['灶具'],
    '蒸烤微合计':['烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微'],
    '灶集成':['灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机']}
productgroupsset_map_1 = {'灶具': '灶具',
                    '烤箱': '蒸烤微合计',
                    '蒸箱': '蒸烤微合计',
                    '微波炉': '蒸烤微合计',
                    '蒸烤烹饪机': '蒸烤微合计',
                    '蒸烤微烹饪机': '蒸烤微合计',
                    '蒸微': '蒸烤微合计',
                    '灶消烹饪机': '灶集成',
                    '灶蒸烹饪机': '灶集成',
                    '灶蒸烤烹饪机': '灶集成',
                    '灶烤烹饪机': '灶集成'}

### 数据清洗

In [2]:
df_mbom = pd.read_excel(fr"D:\000物料报表\通用化报告\1003工厂mbom多行展开.XLSX")
df_work_list = pd.read_excel(fr"D:\000物料报表\通用化报告\烹饪-1003-251031-生产工单.XLSX")

In [3]:
# 处理数据格式
df_mbom['最终父项物料编码'] = df_mbom['最终父项物料编码'].astype(str).str[:13]
df_work_list['物料编码'] = df_work_list['物料编号'].astype(str).str[:13]

In [4]:
# 筛选出有过生产的整机相关数据
worked_set = set(df_work_list['物料编码'])
df_mbom_worked = df_mbom[df_mbom['最终父项物料编码'].isin(worked_set)].reset_index(drop=True)
# 保留最终父和子，并去重
df_mbom_worked = df_mbom_worked[['最终父项物料编码','子项物料编码']].drop_duplicates().reset_index(drop=True)

In [5]:
df_mbom_worked

             最终父项物料编码         子项物料编码
0       1002000400052  1102000407340
1       1002000400052  1102000407490
2       1002000400053  1102000400370
3       1002000400053  1102000407160
4       1002000400053  1102000407190
...               ...            ...
142289  1009001300016  1402040700170
142290  1009001300017  1402040700170
142291  1009001300013  1402040700170
142292  1009001300014  1402040700170
142293  1009001300015  1402040700170

[142294 rows x 2 columns]

In [6]:
df_plm = pd.read_excel(fr"D:\000物料报表\通用化报告\产品生命周期状态全表.xlsx")
df_plm['物料号'] = df_plm['物料号'].astype(str).str.strip().str[:13]
df_plm

e:\python\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,产品线,产品组,标准型号,是否标准型号,简化型号,国内/海外,物料号,关联项目,产品所有者,产品型号,当前评审阶段,产品状态,产品状态开始时间,下属渠道,对应渠道状态,开始销售时间,退市预警时间,停止销售时间,停止发货时间,剩余负卖生产数量
0,烹饪厨电产品线,灶具,02-CS34BW,是,02-CS34BW,国内,nan,P-2022088-02-CS34BW,褚武建,02-CS34BW,PDCP,开发,6/8/2022 1:20:51 PM,零售,未售,NaN,NaN,NaN,NaN,0.0
1,烹饪厨电产品线,灶具,02-CS34BW,是,02-CS34BW,国内,nan,P-2022088-02-CS34BW,褚武建,02-CS34BW,PDCP,开发,6/8/2022 1:20:51 PM,电商,未售,NaN,NaN,NaN,NaN,0.0
2,烹饪厨电产品线,灶具,02-CS34BW,是,02-CS34BW,国内,nan,P-2022088-02-CS34BW,褚武建,02-CS34BW,PDCP,开发,6/8/2022 1:20:51 PM,工程,未售,NaN,NaN,NaN,NaN,0.0
3,洗碗机产品线,水槽洗碗机,NaN,NaN,1,国内,nan,NaN,王伟,1,NaN,作废,11/30/2023 6:48:57 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,净热产品线,热水器,JSG15-0606,NaN,JSG15-0606,国内,1004000200090,NaN,PlatformAdmin,10T-JSG15-0606FR,结项阶段,停止发货,11/30/2023 6:49:04 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9212,油烟机产品线,吸油烟机,苍穹V5R1,是,苍穹V5R1,国内,nan,P-2025209-苍穹V5R1平台开发,周佳杰,苍穹V5R1,NaN,开发,9/17/2025 8:49:02 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9213,油烟机产品线,吸油烟机,轩辕V1R1,是,轩辕V1R1,国内,nan,P-2023108-轩辕V1R1平台,王紫军,轩辕V1R1,结项阶段,量产,11/30/2023 6:48:56 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9214,油烟机产品线,吸油烟机,轩辕V1R1C02,是,轩辕V1R1C02,国内,nan,P-2024133-轩辕V1R1C02 平台开发,徐烽,轩辕V1R1C02,结项阶段,样机,6/27/2024 9:09:52 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9215,油烟机产品线,吸油烟机,轩辕V1R1C03,是,轩辕V1R1C03,国内,nan,P-2025113-轩辕V1R1C03平台,谢靖宇,轩辕V1R1C03,TR3,开发,6/9/2025 2:05:58 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9216,油烟机产品线,吸油烟机,长琴V1R1,是,长琴V1R1,国内,nan,P-2023114-长琴V1R1平台,徐想,长琴V1R1,结项阶段,量产,11/30/2023 6:48:56 PM,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# 把产品相关信息匹配进去
df_calu = pd.merge(df_mbom_worked, df_plm[['物料号', '标准型号', '国内/海外', '产品组']].drop_duplicates().reset_index(drop=True), left_on='最终父项物料编码',right_on='物料号', how='left')
df_calu[df_calu['最终父项物料编码'].isnull()]
print(len(df_calu))

142294

In [8]:
# 每个标准型号只保留最老的产品数据
stand_old_data  = df_calu.groupby('标准型号',as_index=False).agg(
                                                        最终父项物料编码  = ('最终父项物料编码', 'min')            
)
stand_old_data

# 对于每个标准型号只保留最老的产品数据
df_calu1 = df_calu[df_calu['最终父项物料编码'].isin(stand_old_data['最终父项物料编码'])].reset_index(drop=True)
df_calu1['产品组'].value_counts()
df_calu1
print(len(df_calu1))
# 剔除海外的物料
df_calu1 = df_calu1[df_calu1['国内/海外']=='国内']
df_calu1
print(len(df_calu1))

65920
58756

In [ ]:
df_calu1.to_excel(fr'D:\000物料报表\通用化报告\需要导出信息的零件集合.xlsx',index=False)

In [9]:
# 剔除掉虚拟物料和服务专用配件
df_filter1 = pd.read_excel(fr"D:\000物料报表\通用化报告\虚拟-服务专用配件-图号判断.XLSX")
df_calu1['物料描述'] = df_calu1['子项物料编码'].map(dict(zip(df_filter1['物料编码'], df_filter1['物料描述'])))
df_calu1['图号'] = df_calu1['子项物料编码'].map(dict(zip(df_filter1['物料编码'], df_filter1['图号'])))
df_calu1['是否服务专用配件'] = df_calu1['子项物料编码'].map(dict(zip(df_filter1['物料编码'], df_filter1['是否服务专用配件'])))
df_calu1['是否虚拟物料'] = df_calu1['子项物料编码'].map(dict(zip(df_filter1['物料编码'], df_filter1['是否虚拟物料'])))
print(len(df_calu1))
# 剔除掉虚拟物料和服务专用配件
df_calu1 = df_calu1[(df_calu1['是否服务专用配件']!='X') & (df_calu1['是否虚拟物料']!='X')].reset_index(drop=True)
print(len(df_calu1))
# 只保留11开头的子项物料编码
df_calu1 = df_calu1[df_calu1['子项物料编码'].str.startswith('11')].reset_index(drop=True)
print(len(df_calu1))
# 剔除图号结尾是-0001，-0002，-0003...-0009,到-0099的物料
df_calu1 = df_calu1[~df_calu1['图号'].str.contains(r'-00\d{2}$', na=False)]
print(len(df_calu1))

58756
57408
34371
33697

In [10]:
# 剔除工艺中间件、散装物料、关键字剔除
df_filter2 = pd.read_excel(fr"D:\000物料报表\通用化报告\物料_零件族.xlsx")
df_filter2['物料编码'] = df_filter2['物料编码'].astype(str).str.strip().str[:13]
df_calu1['零件族'] = df_calu1['子项物料编码'].map(dict(zip(df_filter2['物料编码'], df_filter2['零件族'])))
df_calu1
print(len(df_calu1))
# 剔除零件族种包含标贴、说明书、信息码、接线图、附件、插页、铭牌、包装图、公用、标识、共用、手册、操作指引、操作说明、菜谱、印刷品
df_calu1 = df_calu1[~df_calu1['零件族'].str.contains('印刷品|壳体组件-消毒柜|钣金组件-消毒柜', na=False)].reset_index(drop=True)
df_calu1
print(len(df_calu1))

33697
30828

In [16]:
# 聚合一个新的产品组，作为统计维度
df_calu1['产品组1'] = df_calu1['产品组'].map(productgroupsset_map_1)
df_calu1['产品组1'].value_counts(),len(df_calu1)
df_calu1.to_excel(fr"D:\000物料报表\通用化报告\明细表.xlsx",index=False)

In [12]:
df_calu1
df_calu1.groupby('产品组1')['最终父项物料编码'].nunique()

产品组1
灶具       104
灶集成       29
蒸烤微合计     63
Name: 最终父项物料编码, dtype: int64

In [17]:
# 统计每个产品组内部，各个零部件的共同型号数
df_result1 = df_calu1.groupby(['产品组1','子项物料编码'],as_index=False).agg(
                                                        零件共同型号数=('最终父项物料编码','nunique'),
                                                        零件归属型号数=('最终父项物料编码',lambda x: list(x.unique()))
)
df_result1

,产品组1,子项物料编码,零件共同型号数,零件归属型号数
0,灶具,1101001900820,4,"[1002000500084, 1002000600120, 1002000600126, ..."
1,灶具,110100210551B,1,[1002003500069]
2,灶具,110100280417A,1,[1002004400022]
3,灶具,110200020720I,1,[1002002100239]
4,灶具,110200020721I,1,[1002002100239]
...,...,...,...,...
6205,蒸烤微合计,1109002100290,2,"[1009001100019, 1009001100026]"
6206,蒸烤微合计,1109002100560,3,"[1009000600031, 1009000600033, 1009000600034]"
6207,蒸烤微合计,1109002100570,34,"[1009000600001, 1009000600004, 1009000600008, ..."
6208,蒸烤微合计,1109002100630,2,"[1009001100019, 1009001100026]"
6209,蒸烤微合计,1118000303520,7,"[1009000600025, 1009000600026, 1009000600030, ..."

In [18]:
df_result2 = df_result1.groupby(['产品组1'],as_index=False).agg(
                                                        通用化零件数=('零件共同型号数',lambda x: x[x>1].count()),
                                                        通用2次以上的零件数=('零件共同型号数',lambda x: x[x>=2].count()),
                                                        通用3次以上的零件数=('零件共同型号数',lambda x: x[x>=3].count()),
                                                        通用4次以上的零件数=('零件共同型号数',lambda x: x[x>=4].count()),
                                                        通用5次以上的零件数=('零件共同型号数',lambda x: x[x>=5].count()),
                                                        通用6次以上的零件数=('零件共同型号数',lambda x: x[x>=6].count()),
                                                        零部件数=('子项物料编码','nunique')

)
df_result2

,产品组1,通用化零件数,通用2次以上的零件数,通用3次以上的零件数,通用4次以上的零件数,通用5次以上的零件数,通用6次以上的零件数,零部件数
0,灶具,921,921,584,412,332,278,1923
1,灶集成,1230,1230,647,528,361,306,1832
2,蒸烤微合计,1400,1400,1070,807,582,414,2455

In [ ]:
df_result2['通用化零件数占比'] = df_result2['通用化零件数']/df_result2['零部件数']
df_result2.to_excel(fr"D:\000物料报表\通用化报告\通用化统计报告.xlsx",index=False)