In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

### MAP关系汇总

In [ ]:
Channel_map = {
'工程': '工程',
'零售':'零售',
'电商不可售':'电商',
'借出渠道':'无',
'新品':'电商',
'战略电商':'电商',
'转出渠道':'无',
'每誉':'每誉',
'渠道':'无',
'海外':'海外',
'调出渠道':'无'
}
productgroup_list = ['吸油烟机','灶具','烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微','灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','消毒柜','热水器','两用炉','家用净水机','商用净水机','水槽洗碗机','嵌入式洗碗机']
#用于合并计算
productgroupset_map = {
    '蒸烤微合计':['烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微'],
    '灶集成':['灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机'],
    '烹饪产品线合计':['灶具','烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微','灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机'],
    '热水器两用炉合计':['热水器','两用炉'],
    '净热产品线合计':['消毒柜','热水器','两用炉','家用净水机','商用净水机'],
    '洗碗机产品线合计':['水槽洗碗机','嵌入式洗碗机'],
    '国内合计':['吸油烟机','灶具','烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微','灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','消毒柜','热水器','两热炉','家用净水机','商用净水机','水槽洗碗机','嵌入式洗碗机'],
}
productgroup_list2 = ['吸油烟机','灶具','烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微','蒸烤微合计','灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶集成','烹饪产品线合计','消毒柜','热水器','两用炉','热水器两用炉合计','家用净水机','商用净水机','净热产品线合计','水槽洗碗机','嵌入式洗碗机','洗碗机产品线合计','国内合计']
len(productgroup_list2)

25

### 获取物流体系的文件夹中的文件路劲和对应规则的sheetname。并将这些数据进行上写拼接（只保留了编码，渠道，发货数量）

In [26]:
#将这些excel的表格数据进行上下拼接，只要字段：商品编码、商品名称、渠道、实际出库数量
folder_path = r"C:\Users\zhangbon\Desktop\报告\单型号贡献\物流发货1-8月"  # 请替换为实际的文件夹路径
excel_files = []
for root, dirs, files in os.walk(folder_path):
    for file in files:
        sheet_names = file[5:].replace(file[-5:],'')
        if (file.endswith('.xlsx') or file.endswith('.xls')) and not file.startswith('~$'):
            file_path = os.path.join(root, file)
            excel_files.append((file, sheet_names, file_path))
print(excel_files)

[('2025年1月明细.xlsx', '1月明细', 'C:\\Users\\zhangbon\\Desktop\\报告\\单型号贡献\\物流发货1-8月\\2025年1月明细.xlsx'), ('2025年2月明细.xlsx', '2月明细', 'C:\\Users\\zhangbon\\Desktop\\报告\\单型号贡献\\物流发货1-8月\\2025年2月明细.xlsx'), ('2025年3月明细.xlsx', '3月明细', 'C:\\Users\\zhangbon\\Desktop\\报告\\单型号贡献\\物流发货1-8月\\2025年3月明细.xlsx'), ('2025年4月明细.xlsx', '4月明细', 'C:\\Users\\zhangbon\\Desktop\\报告\\单型号贡献\\物流发货1-8月\\2025年4月明细.xlsx'), ('2025年5月明细.xlsx', '5月明细', 'C:\\Users\\zhangbon\\Desktop\\报告\\单型号贡献\\物流发货1-8月\\2025年5月明细.xlsx'), ('2025年6月明细.xlsx', '6月明细', 'C:\\Users\\zhangbon\\Desktop\\报告\\单型号贡献\\物流发货1-8月\\2025年6月明细.xlsx'), ('2025年7月明细.xlsx', '7月明细', 'C:\\Users\\zhangbon\\Desktop\\报告\\单型号贡献\\物流发货1-8月\\2025年7月明细.xlsx'), ('2025年8月明细.xlsx', '8月明细', 'C:\\Users\\zhangbon\\Desktop\\报告\\单型号贡献\\物流发货1-8月\\2025年8月明细.xlsx')]

In [27]:
#如果有报错请提示报错信息
df = pd.DataFrame()
for file in excel_files:
    try:
        df_temp = pd.read_excel(file[2], sheet_name=file[1])
        print(f'成功读取{file[0]}的{file[1]}表')
    except:
        print(f'读取{file[0]}的{file[1]}表失败')
    if '实际总数量' in df_temp.columns:
        df_temp = df_temp.rename(columns={'实际总数量':'实际出库数量'})
    df_temp = df_temp[['商品编码', '渠道', '实际出库数量']]
    df = pd.concat([df, df_temp], axis=0)
df

成功读取2025年1月明细.xlsx的1月明细表
成功读取2025年2月明细.xlsx的2月明细表
成功读取2025年3月明细.xlsx的3月明细表
成功读取2025年4月明细.xlsx的4月明细表
成功读取2025年5月明细.xlsx的5月明细表
成功读取2025年6月明细.xlsx的6月明细表
成功读取2025年7月明细.xlsx的7月明细表
成功读取2025年8月明细.xlsx的8月明细表

                商品编码  渠道 实际出库数量
0      1009001100002  工程      1
1      1001002100022  工程      2
2      1002003400032  工程      2
3      1001002000018  工程      1
4      1003000500029  工程      1
...              ...  ..    ...
48452  1001001500100  电商     -5
48453  1004000900011  电商   -100
48454  1004001300005  电商    -50
48455  1002003400279  电商   -300
48456  1001002100082  电商    -12

[538665 rows x 3 columns]

### 处理历史残留（财务的发货数据，将其转化为编码，名称，渠道，出库数量的形式）

In [28]:
#将这些excel的表格数据进行上下拼接，只要字段：商品编码、商品名称、渠道、实际出库数量
folder_path = r"C:\Users\zhangbon\Desktop\报告\单型号贡献\财务9-12月"  # 请替换为实际的文件夹路径
excel_files = []
for root, dirs, files in os.walk(folder_path):
    for file in files:
        sheet_names = file[5:].replace(file[-5:],'')
        if (file.endswith('.xlsx') or file.endswith('.xls')) and not file.startswith('~$'):
            file_path = os.path.join(root, file)
            excel_files.append((file, sheet_names, file_path))
print(excel_files)

[('2024年10月明细.xlsx', '10月明细', 'C:\\Users\\zhangbon\\Desktop\\报告\\单型号贡献\\财务9-12月\\2024年10月明细.xlsx'), ('2024年11月明细.xlsx', '11月明细', 'C:\\Users\\zhangbon\\Desktop\\报告\\单型号贡献\\财务9-12月\\2024年11月明细.xlsx'), ('2024年12月明细.xlsx', '12月明细', 'C:\\Users\\zhangbon\\Desktop\\报告\\单型号贡献\\财务9-12月\\2024年12月明细.xlsx'), ('2024年9月明细.xlsx', '9月明细', 'C:\\Users\\zhangbon\\Desktop\\报告\\单型号贡献\\财务9-12月\\2024年9月明细.xlsx')]

In [29]:
caiwu_shouru = {'商品编码':[],'渠道':[],'实际出库数量':[]}
for file in excel_files:
    try:
        df_temp = pd.read_excel(file[2], sheet_name=file[1])
        print(f'成功读取{file[0]}的{file[1]}表')
    except:
        print(file[0], file[1])
    for index,row in df_temp.iterrows():
        if row['零售'] > 0:
            caiwu_shouru['商品编码'].append(row['物料编码'])
            caiwu_shouru['渠道'].append('零售')
            caiwu_shouru['实际出库数量'].append(row['零售'])
        if row['工程'] >0:
            caiwu_shouru['商品编码'].append(row['物料编码'])
            caiwu_shouru['渠道'].append('工程')
            caiwu_shouru['实际出库数量'].append(row['工程'])
        if row['电商'] >0:
            caiwu_shouru['商品编码'].append(row['物料编码'])
            caiwu_shouru['渠道'].append('电商')
            caiwu_shouru['实际出库数量'].append(row['电商'])
        if row['合计-发货'] - row['零售'] - row['工程'] - row['电商'] != 0:
            caiwu_shouru['商品编码'].append(row['物料编码'])
            caiwu_shouru['渠道'].append('非零售工程电商')
            caiwu_shouru['实际出库数量'].append(row['合计-发货'] - row['零售'] - row['工程'] - row['电商'])

df_caiwu = pd.DataFrame(caiwu_shouru)
df_caiwu
    #

成功读取2024年10月明细.xlsx的10月明细表
成功读取2024年11月明细.xlsx的11月明细表
成功读取2024年12月明细.xlsx的12月明细表
成功读取2024年9月明细.xlsx的9月明细表

               商品编码       渠道  实际出库数量
0     1001000200087       零售       1
1     1001000900383       工程     801
2     1001001500121       电商    6022
3     1001002000027       零售    1501
4     1001002000027       电商     338
...             ...      ...     ...
4806  1021000400003  非零售工程电商     240
4807  1021000400007  非零售工程电商     810
4808  1021000400008  非零售工程电商     150
4809  1021000200003  非零售工程电商     300
4810  1021000200004  非零售工程电商     400

[4811 rows x 3 columns]

In [44]:
# df_caiwu[df_caiwu['商品编码']==1013000500000]

### 将财务和物流的数据进行拼接,并进行渠道清洗

In [33]:
df = pd.concat([df, df_caiwu], axis=0)
df = df.reset_index(drop=True)
df['渠道'] = df['渠道'].map(Channel_map).fillna('非零售工程电商')
df = df[df['渠道']!='无']
df

                 商品编码       渠道 实际出库数量
0       1009001100002       工程      1
1       1001002100022       工程      2
2       1002003400032       工程      2
3       1001002000018       工程      1
4       1003000500029       工程      1
...               ...      ...    ...
543471  1021000400003  非零售工程电商    240
543472  1021000400007  非零售工程电商    810
543473  1021000400008  非零售工程电商    150
543474  1021000200003  非零售工程电商    300
543475  1021000200004  非零售工程电商    400

[543454 rows x 3 columns]

### 将产品组信息、核算价匹配进去，计算各个渠道的统计值

In [34]:
# 复制df
df1 = df.copy()
df1[['商品编码','渠道']] = df1[['商品编码','渠道']].astype(str)
df1[['实际出库数量']] = df1[['实际出库数量']].astype(float)
df_product_group = pd.read_excel(r"C:\Users\zhangbon\Desktop\报告\单型号贡献\产品生命周期状态全表20250703.xlsx")
df_product_group[['物料号','标准型号','国内/海外']] = df_product_group[['物料号','标准型号','国内/海外']].astype(str)
df_product_group = df_product_group[df_product_group['物料号'].str.len()>10]
# df_product_group

In [35]:
#产品组对照关系
product_group_map = {}
for index,row in df_product_group.iterrows():
    product_group_map[row['物料号']] = row['产品组']
print(product_group_map)
#标准型号对照关系
product_standard = {}
for index,row in df_product_group.iterrows():
    product_standard[row['物料号']] = row['标准型号']
#记录国内/海外状态
product_country = {}
for index,row in df_product_group.iterrows():
    product_country[row['物料号']] = row['国内/海外']

{'1004000200090': '热水器', '1004000200079': '热水器', '1004000200084': '热水器', '1004000200035': '热水器', '1004000200060': '热水器', '1004000100029': '热水器', '1004000200095': '热水器', '1004000200100': '热水器', '1004000200019': '热水器', '1004000100050': '热水器', '1004000200039': '热水器', '1004000100048': '热水器', '1002001000020': '灶具', '1002001300020': '灶具', '1002001300021': '灶具', '1002001400020': '灶具', '1002001400021': '灶具', '1002001400022': '灶具', '1002001400023': '灶具', '1002001800020': '灶具', '1002001800021': '灶具', '1002001800022': '灶具', '1002001900020': '灶具', '1002002500089': '灶具', '1002001900407': '灶具', '1002002900049': '灶具', '1002002900054': '灶具', '1002002900050': '灶具', '1002002900020': '灶具', '1002002900053': '灶具', '1002001900024': '灶具', '1002001900021': '灶具', '1002002900056': '灶具', '1002001900025': '灶具', '1002001900027': '灶具', '1002001900022': '灶具', '1002002900051': '灶具', '1002002900102': '灶具', '1002001900023': '灶具', '1002001900026': '灶具', '1002001900028': '灶具', '1002001900029': '灶具', '1002001900030': '灶具', '1002001900031': '灶具', '1002001900032': '灶具', '1002001900033': '灶具', '1002001900365': '灶具', '1002001900034': '灶具', '1002002900103': '灶具', '1002001900035': '灶具', '1002001900036': '灶具', '1002001900037': '灶具', '1002001900005': '灶具', '1002002600020': '灶具', '1002001900038': '灶具', '1002001400024': '灶具', '1002001400025': '灶具', '1002001800256': '灶具', '1002001800001': '灶具', '1002001800023': '灶具', '1002001800024': '灶具', '1002003700083': '灶具', '1002003500068': '灶具', '1002002900021': '灶具', '1002002900022': '灶具', '1002002900023': '灶具', '1002002900024': '灶具', '1002002900025': '灶具', '1002002900026': '灶具', '1002002900027': '灶具', '1002002900028': '灶具', '1002003400134': '灶具', '1002003400111': '灶具', '1002003400101': '灶具', '1002003400112': '灶具', '1002003400100': '灶具', '1002003400280': '灶具', '1002003400201': '灶具', '1002002500121': '灶具', '1002002500128': '灶具', '1002002500120': '灶具', '1002002500132': '灶具', '1002002500131': '灶具', '1002002500125': '灶具', '1002002500130': '灶具', '1002002500020': '灶具', '1002002500090': '灶具', '1002002500097': '灶具', '1002002500102': '灶具', '1002002500108': '灶具', '1002002500111': '灶具', '1002002500021': '灶具', '1002002500085': '灶具', '1002002500104': '灶具', '1002002500113': '灶具', '1002002500022': '灶具', '1002002500023': '灶具', '1002002500091': '灶具', '1002002500024': '灶具', '1002002500083': '灶具', '1002002600021': '灶具', '1002002500117': '灶具', '1002002500129': '灶具', '1002002500122': '灶具', '1002002500118': '灶具', '1002002500124': '灶具', '1002002500110': '灶具', '1002002500109': '灶具', '1002002500119': '灶具', '1002002500116': '灶具', '1002002600022': '灶具', '1002002500086': '灶具', '1002002500105': '灶具', '1002002500112': '灶具', '1002002500025': '灶具', '1002000900020': '灶具', '1002000900021': '灶具', '1002000900022': '灶具', '1002000900023': '灶具', '1002001300022': '灶具', '1002001300023': '灶具', '1002001300024': '灶具', '1002001300025': '灶具', '1002001000021': '灶具', '1002001000022': '灶具', '1002001000023': '灶具', '1002001500020': '灶具', '1002001600020': '灶具', '1002001600021': '灶具', '1002001600022': '灶具', '1002001600023': '灶具', '1002001600024': '灶具', '1002001600025': '灶具', '1002002600023': '灶具', '1002002600030': '灶具', '1002002600031': '灶具', '1002002600032': '灶具', '1002002600024': '灶具', '1002002600025': '灶具', '1002002600026': '灶具', '1002002600027': '灶具', '1002002600028': '灶具', '1002002600029': '灶具', '1002002600033': '灶具', '1002002600034': '灶具', '1002002600035': '灶具', '1002002600036': '灶具', '1002002600038': '灶具', '1002002600037': '灶具', '1002002600039': '灶具', '1002002600040': '灶具', '1002002600041': '灶具', '1002002600042': '灶具', '1002002600043': '灶具', '1002002600044': '灶具', '1002002600045': '灶具', '1002002600046': '灶具', '1002002600047': '灶具', '1002002600048': '灶具', '1002002600049': '灶具', '1002002600050': '灶具', '1002002600051': '灶具', '1002002600052': '灶具', '1002001600026': '灶具', '1002001600027': '灶具', '1002001600028': '灶具', '1004000200075': '热水器', '1004000200091': '热水器', '1004000200058': '热水器', '1004000200080': '热水器', '1004000200085': '热水器', '1004000100039': '热水器', '1004000200061': '热水器', '1004000200049': '热水器', '1004000200096': '热水器', '1004000200101': '热水器', '1004000200022': '热水器', '1004000100020': '热水器', '1004000100071': '热水器', '1004000100055': '热水器', '1004000200023': '热水器', '1004000200077': '热水器', '1004000200040': '热水器', '1004000100033': '热水器', '1004000100021': '热水器', '1004000100053': '热水器', '1004000100051': '热水器', '1004000100056': '热水器', '1002001000024': '灶具', '1002001000025': '灶具', '1002001000026': '灶具', '1002001000027': '灶具', '1002001000205': '灶具', '1004000700012': '热水器', '1004900000003': '热水器', '1004000700010': '热水器', '1002002700020': '灶具', '1004000100253': '热水器', '1004900000006': '热水器', '1002001300026': '灶具', '1002001300027': '灶具', '1002001300163': '灶具', '1002001400026': '灶具', '1002001400027': '灶具', '1002001400028': '灶具', '1002001400029': '灶具', '1002001400030': '灶具', '1002001400031': '灶具', '1002001400032': '灶具', '1002001400033': '灶具', '1002001400034': '灶具', '1002001400035': '灶具', '1002001400036': '灶具', '1002001400037': '灶具', '1002001800025': '灶具', '1002001800026': '灶具', '1002001800353': '灶具', '1002001800027': '灶具', '1002001800028': '灶具', '1002001800029': '灶具', '1002001800030': '灶具', '1002001800253': '灶具', '1002001900040': '灶具', '1002001900041': '灶具', '1002001900042': '灶具', '1002002600105': '灶具', '1002002600053': '灶具', '1002001900043': '灶具', '1002001900360': '灶具', '1002001900044': '灶具', '1002001900039': '灶具', '1002001900049': '灶具', '1002001900045': '灶具', '1002001900047': '灶具', '1002001900408': '灶具', '1002001900050': '灶具', '1002001900046': '灶具', '1002001900048': '灶具', '1002001900457': '灶具', '1002001900391': '灶具', '1002001900004': '灶具', '1002001900361': '灶具', '1002002900052': '灶具', '1002001900055': '灶具', '1002001900058': '灶具', '1002001900051': '灶具', '1002001900056': '灶具', '1002001900389': '灶具', '1002001900059': '灶具', '1002900000001': '灶具', '1002001900052': '灶具', '1002001900057': '灶具', '1002001900053': '灶具', '1002001900061': '灶具', '1002001900362': '灶具', '1002001900358': '灶具', '1002001900393': '灶具', '1002001900062': '灶具', '1002001900054': '灶具', '1002001900063': '灶具', '1002001900064': '灶具', '1002001900065': '灶具', '1002001900066': '灶具', '1002001900364': '灶具', '1002001900067': '灶具', '1002001900068': '灶具', '1002001900069': '灶具', '1002001900006': '灶具', '1002001900363': '灶具', '1002001900070': '灶具', '1002001900002': '灶具', '1002001900359': '灶具', '1002001900367': '灶具', '1002002600104': '灶具', '1002001900377': '灶具', '1002001400038': '灶具', '1002001400039': '灶具', '1002001400040': '灶具', '1002001400041': '灶具', '1002001400042': '灶具', '1002001400043': '灶具', '1002001800031': '灶具', '1002001800032': '灶具', '1002001800254': '灶具', '1002001800033': '灶具', '1002001800034': '灶具', '1002001800258': '灶具', '1002001800035': '灶具', '1002001800036': '灶具', '1002001800037': '灶具', '1002001800038': '灶具', '1002001800255': '灶具', '1002001800039': '灶具', '1002003700088': '灶具', '1002003500054': '灶具', '1002003500061': '灶具', '1002003700042': '灶具', '1002003700021': '灶具', '1002003700048': '灶具', '1002003700057': '灶具', '1002003700092': '灶具', '1002003700079': '灶具', '1002003700093': '灶具', '1002003700056': '灶具', '1002002900029': '灶具', '1002002900030': '灶具', '1002002900031': '灶具', '1002002900032': '灶具', '1002002900033': '灶具', '1002002900034': '灶具', '1002002900035': '灶具', '1002002900036': '灶具', '1002002900037': '灶具', '1002002900038': '灶具', '1002002900039': '灶具', '1002002900040': '灶具', '1002002900041': '灶具', '1002002900042': '灶具', '1002002900043': '灶具', '1002002900044': '灶具', '1002002900045': '灶具', '1002003400148': '灶具', '1002003400149': '灶具', '1002003400195': '灶具', '1002003400200': '灶具', '1002003400256': '灶具', '1002003400266': '灶具', '1002003400269': '灶具', '1002003400281': '灶具', '1002003400272': '灶具', '1002003400304': '灶具', '1002003400033': '灶具', '1002003400271': '灶具', '1002003400056': '灶具', '1002003400129': '灶具', '1002003400009': '灶具', '1002003400055': '灶具', '1002003400070': '灶具', '1002003400251': '灶具', '1002003400301': '灶具', '1002003400034': '灶具', '1002003400270': '灶具', '1002003400057': '灶具', '1002003400024': '灶具', '1002003400069': '灶具', '1002003400161': '灶具', '1002003400282': '灶具', '1002003400213': '灶具', '1002002500106': '灶具', '1002002500098': '灶具', '1002002500101': '灶具', '1002002500107': '灶具', '1002002500092': '灶具', '1002002500099': '灶具', '1002002500100': '灶具', '1002002500114': '灶具', '1002002500127': '灶具', '1002002500087': '灶具', '1002002500126': '灶具', '1002002500123': '灶具', '1002002500088': '灶具', '1002002500093': '灶具', '1002002500103': '灶具', '1002002500115': '灶具', '1002001300028': '灶具', '1002001000028': '灶具', '1002001000029': '灶具', '1002001500021': '灶具', '1002001700020': '灶具', '1002001700021': '灶具', '1002001700022': '灶具', '1002001700023': '灶具', '1002001600030': '灶具', '1002001600031': '灶具', '1002001600032': '灶具', '1002001600033': '灶具', '1002001600029': '灶具', '1002001600034': '灶具', '1002001600035': '灶具', '1002000600020': '灶具', '1002002600054': '灶具', '1002002600055': '灶具', '1002002600056': '灶具', '1002002600069': '灶具', '1002002600057': '灶具', '1002002600058': '灶具', '1002002600059': '灶具', '1002002600060': '灶具', '1002002600061': '灶具', '1002002600062': '灶具', '1002002600063': '灶具', '1002002600064': '灶具', '1002002600065': '灶具', '1002002600066': '灶具', '1002002600103': '灶具', '1002002600067': '灶具', '1002002600068': '灶具', '1002001600036': '灶具', '1002001600037': '灶具', '1002001600038': '灶具', '1002001600039': '灶具', '1002001600040': '灶具', '1009000900031': '灶蒸烤烹饪机', '1009000900030': '灶蒸烤烹饪机', '1009000900039': '灶蒸烤烹饪机', '1004000200076': '热水器', '1004000200092': '热水器', '1004000200056': '热水器', '1004000200059': '热水器', '1004000200081': '热水器', '1004000200074': '热水器', '1004000200086': '热水器', '1004000200037': '热水器', '1004000200062': '热水器', '1004000200050': '热水器', '1004000200010': '热水器', '1004000200097': '热水器', '1004000200102': '热水器', '1004000200016': '热水器', '1004000100013': '热水器', '1004000100072': '热水器', '1004000100045': '热水器', '1004000200033': '热水器', '1004000200078': '热水器', '1004000200041': '热水器', '1004000100032': '热水器', '1004000100015': '热水器', '1004000100043': '热水器', '1004000100011': '热水器', '1004000100067': '热水器', '1004000100046': '热水器', '1002001000031': '灶具', '1002001000030': '灶具', '1004000700013': '热水器', '1004000700011': '热水器', '1002002700021': '灶具', '1004000200093': '热水器', '1004000200082': '热水器', '1004000200087': '热水器', '1004000200063': '热水器', '1004000200012': '热水器', '1004000200098': '热水器', '1004000200103': '热水器', '1004000200026': '热水器', '1004000100025': '热水器', '1004000100073': '热水器', '1004000100060': '热水器', '1004000100058': '热水器', '1004000100068': '热水器', '1002001400044': '灶具', '1002001400045': '灶具', '1002001900404': '灶具', '1002001900390': '灶具', '1002001900003': '灶具', '1002001900392': '灶具', '1002001900071': '灶具', '1002002900055': '灶具', '1002001900001': '灶具', '1002001400046': '灶具', '1002002900046': '灶具', '1002002900047': '灶具', '1002002900048': '灶具', '1002003400087': '灶具', '1002003400265': '灶具', '1002001600041': '灶具', '1004000200088': '热水器', '1004000200064': '热水器', '1004000200029': '热水器', '1004000100023': '热水器', '1004000100062': '热水器', '1004000200042': '热水器', '1004000100034': '热水器', '1004000200094': '热水器', '1004000200057': '热水器', '1004000200083': '热水器', '1004000200204': '热水器', '1004000200089': '热水器', '1004000200038': '热水器', '1004000200065': '热水器', '1004000200013': '热水器', '1004000200099': '热水器', '1004000200104': '热水器', '1004000100074': '热水器', '1004000100254': '热水器', '1004000100065': '热水器', '1004000200034': '热水器', '1004000100069': '热水器', '1001002000023': '吸油烟机', '1001002000010': '吸油烟机', '1001002000024': '吸油烟机', '1001002000012': '吸油烟机', '1001002000013': '吸油烟机', '1001002000032': '吸油烟机', '1001002000015': '吸油烟机', '1001002000022': '吸油烟机', '1001002000026': '吸油烟机', '1001002000025': '吸油烟机', '1001002000016': '吸油烟机', '1001002800004': '吸油烟机', '1001002800006': '吸油烟机', '1001002800005': '吸油烟机', '1001002800008': '吸油烟机', '1001002000034': '吸油烟机', '1019000100000': '家用冰箱', '1019000100001': '家用冰箱', '1019000300008': '家用冰箱', '1019000300003': '家用冰箱', '1019000300005': '家用冰箱', '1019000300000': '家用冰箱', '1019000300004': '家用冰箱', '1019000300002': '家用冰箱', '1019000300001': '家用冰箱', '1019000300006': '家用冰箱', '1019000300007': '家用冰箱', '1019000200003': '家用冰箱', '1019000200000': '家用冰箱', '1019000200002': '家用冰箱', '1019000200004': '家用冰箱', '1019000200001': '家用冰箱', '1010000100002': '保温箱', '1010000100003': '保温箱', '1018000300015': '嵌入式洗碗机', '1018000300006': '嵌入式洗碗机', '1018000300007': '嵌入式洗碗机', '1018000300008': '嵌入式洗碗机', '1018000500026': '嵌入式洗碗机', '1018000100011': '嵌入式洗碗机', '1018000100010': '嵌入式洗碗机', '1018000300003': '嵌入式洗碗机', '1018000300004': '嵌入式洗碗机', '1018001100003': '嵌入式洗碗机', '1018001100005': '嵌入式洗碗机', '1018001100010': '嵌入式洗碗机', '1018001100006': '嵌入式洗碗机', '1018001100015': '嵌入式洗碗机', '1001003000000': '吸油烟机', '1001003000001': '吸油烟机', '1015000100004': '大厨管家', '1002000500020': '灶具', '1002000500021': '灶具', '1002000500022': '灶具', '1002000500023': '灶具', '1002000500024': '灶具', '1002000500025': '灶具', '1002000500026': '灶具', '1002000500027': '灶具', '1002000500028': '灶具', '1002000500029': '灶具', '1002000500030': '灶具', '1002000500031': '灶具', '1002000500032': '灶具', '1002000500033': '灶具', '1002000500034': '灶具', '1002000500035': '灶具', '1002000500036': '灶具', '1002000500037': '灶具', '1002000500087': '灶具', '1002000500085': '灶具', '1002000500091': '灶具', '1002000500088': '灶具', '1002000500084': '灶具', '1002000500082': '灶具', '1001001700038': '吸油烟机', '1001001700034': '吸油烟机', '1001001700035': '吸油烟机', '1001001700039': '吸油烟机', '1001001700047': '吸油烟机', '1001001700040': '吸油烟机', '1001001700036': '吸油烟机', '1001001700037': '吸油烟机', '1001001700046': '吸油烟机', '1001001700044': '吸油烟机', '1001001700045': '吸油烟机', '1001001700042': '吸油烟机', '1001001700031': '吸油烟机', '1001001700030': '吸油烟机', '1001001700043': '吸油烟机', '1001001700048': '吸油烟机', '1001001700033': '吸油烟机', '1001001700041': '吸油烟机', '1001001700032': '吸油烟机', '1001001900102': '吸油烟机', '1001001900099': '吸油烟机', '1001001900101': '吸油烟机', '1001001900104': '吸油烟机', '1001001900093': '吸油烟机', '1001001900096': '吸油烟机', '1001001900098': '吸油烟机', '1001001900091': '吸油烟机', '1001001900097': '吸油烟机', '1001001900100': '吸油烟机', '1001001900095': '吸油烟机', '1001001900037': '吸油烟机', '1001001900030': '吸油烟机', '1001001900038': '吸油烟机', '1001001900035': '吸油烟机', '1001001900039': '吸油烟机', '1001001900034': '吸油烟机', '1001001900036': '吸油烟机', '1001001900032': '吸油烟机', '1001001900033': '吸油烟机', '1001001900031': '吸油烟机', '1002000500038': '灶具', '1002000500039': '灶具', '1002000500040': '灶具', '1002000500041': '灶具', '1002000500042': '灶具', '1002000500043': '灶具', '1002000500044': '灶具', '1002000500045': '灶具', '1002000500046': '灶具', '1002000500047': '灶具', '1002000500048': '灶具', '1002000500049': '灶具', '1002000500050': '灶具', '1002000500080': '灶具', '1002000500083': '灶具', '1001000100055': '吸油烟机', '1001001600034': '吸油烟机', '1001001600031': '吸油烟机', '1001001600043': '吸油烟机', '1001001600030': '吸油烟机', '1001001600042': '吸油烟机', '1001001600035': '吸油烟机', '1001001600044': '吸油烟机', '1001001600037': '吸油烟机', '1001001600036': '吸油烟机', '1001001600032': '吸油烟机', '1001001600040': '吸油烟机', '1001001600045': '吸油烟机', '1001001600038': '吸油烟机', '1001001600103': '吸油烟机', '1001001600033': '吸油烟机', '1001001600039': '吸油烟机', '1001001600109': '吸油烟机', '1001001600104': '吸油烟机', '1001001600107': '吸油烟机', '1001001600041': '吸油烟机', '1001001600105': '吸油烟机', '1001001600106': '吸油烟机', '1001001600001': '吸油烟机', '1001001600102': '吸油烟机', '1001001600108': '吸油烟机', '1001001900040': '吸油烟机', '1001000100060': '吸油烟机', '1001000100039': '吸油烟机', '1001000100108': '吸油烟机', '1001000100066': '吸油烟机', '1001000100056': '吸油烟机', '1001000100061': '吸油烟机', '1001000100103': '吸油烟机', '1001000100113': '吸油烟机', '1001000100064': '吸油烟机', '1001000600039': '吸油烟机', '1001000200036': '吸油烟机', '1001000100040': '吸油烟机', '1001000100067': '吸油烟机', '1001000100057': '吸油烟机', '1001000100058': '吸油烟机', '1001000300092': '吸油烟机', '1001000300067': '吸油烟机', '1001000300103': '吸油烟机', '1001000100035': '吸油烟机', '1001000100052': '吸油烟机', '1001000600033': '吸油烟机', '1001000600034': '吸油烟机', '1001000600037': '吸油烟机', '1001000600035': '吸油烟机', '1001000600044': '吸油烟机', '1001000600030': '吸油烟机', '1001000100037': '吸油烟机', '1001000100049': '吸油烟机', '1001000100036': '吸油烟机', '1001000100105': '吸油烟机', '1001000100053': '吸油烟机', '1001000100033': '吸油烟机', '1001000100109': '吸油烟机', '1001000100031': '吸油烟机', '1001000100042': '吸油烟机', '1001000100046': '吸油烟机', '1001000100045': '吸油烟机', '1001000100110': '吸油烟机', '1001000100030': '吸油烟机', '1001000100044': '吸油烟机', '1001000100050': '吸油烟机', '1001000100111': '吸油烟机', '1001000800328': '吸油烟机', '1001000200039': '吸油烟机', '1001000700030': '吸油烟机', '1001000700032': '吸油烟机', '1001000800176': '吸油烟机', '1001000800144': '吸油烟机', '1001000800098': '吸油烟机', '1001000800101': '吸油烟机', '1001000800214': '吸油烟机', '1001000800157': '吸油烟机', '1001000800063': '吸油烟机', '1001000800089': '吸油烟机', '1001000800340': '吸油烟机', '1001000800312': '吸油烟机', '1001000800092': '吸油烟机', '1001000800102': '吸油烟机', '1001000800066': '吸油烟机', '1001000800093': '吸油烟机', '1001000800078': '吸油烟机', '1001000800325': '吸油烟机', '1001000800095': '吸油烟机', '1001000800323': '吸油烟机', '1001000800108': '吸油烟机', '1001000800160': '吸油烟机', '1001000800004': '吸油烟机', '1001000800315': '吸油烟机', '1001000800064': '吸油烟机', '1001000800137': '吸油烟机', '1001000800113': '吸油烟机', '1001000800005': '吸油烟机', '1001000800111': '吸油烟机', '1001000800316': '吸油烟机', '1001000800105': '吸油烟机', '1001000800060': '吸油烟机', '1001000800135': '吸油烟机', '1001000800119': '吸油烟机', '1001000800310': '吸油烟机', '1001000800084': '吸油烟机', '1001000800311': '吸油烟机', '1001000800085': '吸油烟机', '1001000800136': '吸油烟机', '1001000800163': '吸油烟机', '1001000800107': '吸油烟机', '1001000800077': '吸油烟机', '1001000800159': '吸油烟机', '1001000800068': '吸油烟机', '1001000800075': '吸油烟机', '1001000800320': '吸油烟机', '1001000800318': '吸油烟机', '1001000800223': '吸油烟机', '1001000800086': '吸油烟机', '1001000800332': '吸油烟机', '1001000800099': '吸油烟机', '1001000800208': '吸油烟机', '1001000800161': '吸油烟机', '1001000800134': '吸油烟机', '1001000800131': '吸油烟机', '1001000800103': '吸油烟机', '1001000800132': '吸油烟机', '1001000800069': '吸油烟机', '1001000800126': '吸油烟机', '1001000800002': '吸油烟机', '1001000800314': '吸油烟机', '1001000800222': '吸油烟机', '1001000800082': '吸油烟机', '1001000800162': '吸油烟机', '1001000800081': '吸油烟机', '1001000800141': '吸油烟机', '1001000800127': '吸油烟机', '1001000800145': '吸油烟机', '1001000800128': '吸油烟机', '1001000800104': '吸油烟机', '1001000800120': '吸油烟机', '1001000800067': '吸油烟机', '1001000800121': '吸油烟机', '1001000800142': '吸油烟机', '1001000800059': '吸油烟机', '1001000800317': '吸油烟机', '1001000800083': '吸油烟机', '1001000800079': '吸油烟机', '1001000800123': '吸油烟机', '1001000800184': '吸油烟机', '1001000800058': '吸油烟机', '1001000800097': '吸油烟机', '1001000800201': '吸油烟机', '1001000800196': '吸油烟机', '1001000800054': '吸油烟机', '1001000800167': '吸油烟机', '1001000800138': '吸油烟机', '1001000800106': '吸油烟机', '1001000800169': '吸油烟机', '1001000800224': '吸油烟机', '1001000800088': '吸油烟机', '1001000800319': '吸油烟机', '1001000800003': '吸油烟机', '1001000800313': '吸油烟机', '1001000800118': '吸油烟机', '1001000800212': '吸油烟机', '1001000800189': '吸油烟机', '1001000800139': '吸油烟机', '1001000800116': '吸油烟机', '1001000800091': '吸油烟机', '1001000800190': '吸油烟机', '1001000800194': '吸油烟机', '1001000800055': '吸油烟机', '1001000900079': '吸油烟机', '1001000400031': '吸油烟机', '1001000400032': '吸油烟机', '1001000400030': '吸油烟机', '1001000400033': '吸油烟机', '1001000300088': '吸油烟机', '1001000300060': '吸油烟机', '1001000300049': '吸油烟机', '1001000300054': '吸油烟机', '1001000300093': '吸油烟机', '1001000300089': '吸油烟机', '1001000300085': '吸油烟机', '1001000300075': '吸油烟机', '1001000300076': '吸油烟机', '1001000300104': '吸油烟机', '1001000300068': '吸油烟机', '1001000300051': '吸油烟机', '1001000300055': '吸油烟机', '1001000300095': '吸油烟机', '1001000300094': '吸油烟机', '1001000300077': '吸油烟机', '1001000300078': '吸油烟机', '1001000300061': '吸油烟机', '1001000300079': '吸油烟机', '1001000300096': '吸油烟机', '1001000300063': '吸油烟机', '1001000300097': '吸油烟机', '1001000300080': '吸油烟机', '1001000300081': '吸油烟机', '1001000300064': '吸油烟机', '1001000300100': '吸油烟机', '1001000300082': '吸油烟机', '1001000300083': '吸油烟机', '1001000300046': '吸油烟机', '1001000300042': '吸油烟机', '1001000300044': '吸油烟机', '1001000300047': '吸油烟机', '1001000300084': '吸油烟机', '1001000300086': '吸油烟机', '1001000300090': '吸油烟机', '1001000300073': '吸油烟机', '1001000300164': '吸油烟机', '1001000300062': '吸油烟机', '1001000300072': '吸油烟机', '1001000300070': '吸油烟机', '1001000300

In [36]:
df_price = pd.read_excel(r"C:\Users\zhangbon\Desktop\报告\核算价-20250731.xlsx")
df_price['产品编码'] = df_price['产品编码'].astype(str)
df_price['系统核算价'] = df_price['系统核算价'].astype(float)
# df_price

In [37]:
product_price_map = {}
for index, row in df_price.iterrows():
    product_price_map[row['产品编码']] = row['系统核算价']

In [38]:

df1['产品组'] = df1['商品编码'].map(product_group_map)
df1['系统核算价'] = df1['商品编码'].map(product_price_map)
df1['核算价'] = df1['系统核算价'] * df1['实际出库数量']
df1['标准型号'] = df1['商品编码'].map(product_standard)
df1['国内/海外'] = df1['商品编码'].map(product_country)
df1

,商品编码,渠道,实际出库数量,产品组,系统核算价,核算价,标准型号,国内/海外
0,1009001100002,工程,1.0,蒸烤烹饪机,3550.0,3550.0,ZK50-01-F1.i,国内
1,1001002100022,工程,2.0,吸油烟机,1508.0,3016.0,JC03A,国内
2,1002003400032,工程,2.0,灶具,900.0,1800.0,TH3B,国内
3,1001002000018,工程,1.0,吸油烟机,3668.0,3668.0,03-X1A,国内
4,1003000500029,工程,1.0,消毒柜,1550.0,1550.0,ZTD100J-J31,国内
...,...,...,...,...,...,...,...,...
543471,1021000400003,非零售工程电商,240.0,地面手持式清洁机,4200.0,1008000.0,nan,国内
543472,1021000400007,非零售工程电商,810.0,地面手持式清洁机,3522.0,2852820.0,nan,国内
543473,1021000400008,非零售工程电商,150.0,地面手持式清洁机,3522.0,528300.0,QX-V8,国内
543474,1021000200003,非零售工程电商,300.0,地面手持式清洁机,3886.0,1165800.0,Q7Plus-L,国内
543475,1021000200004,非零售工程电商,400.0,地面手持式清洁机,4068.0,1627200.0,Q8,国内

In [42]:
# df1[df1['商品编码'] == '1013000500000']

#### 剔除掉没有匹到产品组的值，并进行产品组和渠道分组聚合，这里要注意补充核算价！！！！！（在这里会输出一个文件用于后续低效和长尾的分析）

In [46]:
out_df = df1.copy()
out_df = out_df[~out_df['产品组'].isnull()]
out_df = out_df[out_df[r'国内/海外']=='国内']
out_df = out_df[out_df['产品组'].isin(productgroup_list)]
#这里要提示哪些数据的系统核算价是空的
print(f'没有系统核算价的是这些数据\n{out_df[out_df['系统核算价'].isnull()]['商品编码'].drop_duplicates()}')
print(len(out_df))

# 这里导出数据用于其他报告的分析
out_df.to_excel(r'C:\Users\zhangbon\Desktop\清洗了物流-财务-渠道-产品组-国内.xlsx',index=False)

没有系统核算价的是这些数据
Series([], Name: 商品编码, dtype: object)
306178

In [21]:
# 1. 先计算每个(产品组+渠道)的标准型号数
channel_counts = out_df.groupby(['产品组', '渠道'])['标准型号'].nunique().reset_index()

# 2. 转换为透视表，让每个渠道成为单独一列
pivot_counts = channel_counts.pivot(
    index='产品组',
    columns='渠道',
    values='标准型号'
).fillna(0).astype(int)  # 缺失的渠道用0填充，并转为整数

# 3. 重命名列名以匹配目标列
pivot_counts = pivot_counts.rename(columns={
    '零售': '零售渠道标准型号数',
    '工程': '工程渠道标准型号数',
    '电商': '电商渠道标准型号数'
})

# 4. 合并回原表，确保每个产品组的所有行都能正确填充
out_df = out_df.merge(pivot_counts, on='产品组', how='left')

# 1. 先计算每个(产品组+渠道)的核算价
channel_counts = out_df.groupby(['产品组', '渠道'])['核算价'].sum().reset_index()

# 2. 转换为透视表，让每个渠道成为单独一列
pivot_counts = channel_counts.pivot(
    index='产品组',
    columns='渠道',
    values='核算价'
).fillna(0).astype(float)  # 缺失的渠道用0填充，并转为整数

# 3. 重命名列名以匹配目标列
pivot_counts = pivot_counts.rename(columns={
    '零售': '零售渠道核算价',
    '工程': '工程渠道核算价',
    '电商': '电商渠道核算价'
})

# 4. 合并回原表，确保每个产品组的所有行都能正确填充
out_df = out_df.merge(pivot_counts, on='产品组', how='left')

out_df['汇总核算价'] = out_df.groupby('产品组')['核算价'].transform('sum')
out_df['汇总标准型号数'] = out_df.groupby('产品组')['标准型号'].transform('nunique')

#将结果规整出来，并去重，只保留产品组维度
out_df1 = out_df[['产品组','零售渠道标准型号数','零售渠道核算价','工程渠道标准型号数','工程渠道核算价','电商渠道标准型号数','电商渠道核算价','汇总标准型号数','汇总核算价']].drop_duplicates()
out_df1 = out_df1.reset_index(drop=True)
all_product_groups = pd.DataFrame({'产品组': productgroup_list})
out_df1 = all_product_groups.merge(out_df1, on='产品组', how='left')
# 3.3 将所有NaN（缺失值）填充为0（产品组列不会有NaN，因为来自all_product_groups）
out_df1 = out_df1.fillna(0)
# out_df.to_excel('C:\\Users\\zhangbon\\Desktop\\单型号贡献-0904.xlsx',index=False)
out_df1

,产品组,零售渠道标准型号数,零售渠道核算价,工程渠道标准型号数,工程渠道核算价,电商渠道标准型号数,电商渠道核算价,汇总标准型号数,汇总核算价
0,吸油烟机,101.0,3.977393e+09,71.0,951001832.0,68.0,1.121377e+09,179.0,7.640243e+09
1,灶具,69.0,1.863339e+09,59.0,482135684.0,56.0,5.588364e+08,105.0,3.710070e+09
2,烤箱,9.0,5.911313e+07,7.0,3595980.0,8.0,4.723550e+06,14.0,7.607758e+07
3,蒸箱,8.0,7.105559e+07,5.0,3386510.0,8.0,5.789900e+06,15.0,9.127360e+07
4,微波炉,4.0,1.183224e+07,3.0,3807290.0,2.0,1.655280e+06,5.0,2.030897e+07
5,蒸烤烹饪机,25.0,6.267113e+08,19.0,57464022.0,37.0,7.430452e+07,47.0,9.021972e+08
6,蒸烤微烹饪机,2.0,7.726500e+06,3.0,1565580.0,3.0,2.767299e+07,6.0,6.310412e+07
7,蒸微,0.0,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,0.000000e+00
8,灶消烹饪机,3.0,3.458743e+07,0.0,0.0,2.0,3.629000e+04,3.0,3.565302e+07
9,灶蒸烹饪机,1.0,5.782800e+05,0.0,0.0,1.0,9.480000e+03,2.0,6.502400e+05
10,灶蒸烤烹饪机,22.0,5.305097e+08,9.0,30005790.0,11.0,8.387900e+05,23.0,5.711737e+08
11,消毒柜,22.0,1.709255e+08,16.0,150045420.0,5.0,4.008314e+07,29.0,4.258160e+08
12,热水器,39.0,3.244426e+08,18.0,21375770.0,37.0,5.526920e+07,63.0,4.781918e+08
13,两用炉,5.0,5.713122e+06,1.0,10632.0,4.0,5.454000e+04,6.0,5.919530e+06
14,家用净水机,26.0,1.959024e+08,11.0,1577220.0,13.0,6.071960e+06,29.0,2.139068e+08
15,商用净水机,0.0,0.000000e+00,0.0,0.0,0.0,0.000000e+00,4.0,3.034840e+06
16,水槽洗碗机,44.0,4.961035e+08,26.0,93243830.0,20.0,5.619830e+07,69.0,7.330177e+08
17,嵌入式洗碗机,31.0,6.339463e+08,32.0,377790325.0,34.0,1.525064e+08,66.0,1.407389e+09

#### 计算产品集合和产品线合计，并排序（产品组集合需要在map中进行维护）

In [22]:
# 依据规则进行蒸烤微合计，灶集成，产品线合计的合计计算，并上下拼接进去
productset_df = pd.DataFrame()
productset_df['产品组'] = productgroupset_map.keys()
productset_df[['零售渠道标准型号数','零售渠道核算价','工程渠道标准型号数','工程渠道核算价','电商渠道标准型号数','电商渠道核算价','汇总标准型号数','汇总核算价']] = 0
for index,row in out_df1.iterrows():
    if row['产品组']  in productgroupset_map['蒸烤微合计']:
        productset_df.loc[productset_df['产品组'] == '蒸烤微合计','零售渠道标准型号数'] += row['零售渠道标准型号数']
        productset_df.loc[productset_df['产品组'] == '蒸烤微合计','零售渠道核算价'] += row['零售渠道核算价']
        productset_df.loc[productset_df['产品组'] == '蒸烤微合计','工程渠道标准型号数'] += row['工程渠道标准型号数']
        productset_df.loc[productset_df['产品组'] == '蒸烤微合计','工程渠道核算价'] += row['工程渠道核算价']
        productset_df.loc[productset_df['产品组'] == '蒸烤微合计','电商渠道标准型号数'] += row['电商渠道标准型号数']
        productset_df.loc[productset_df['产品组'] == '蒸烤微合计','电商渠道核算价'] += row['电商渠道核算价']
        productset_df.loc[productset_df['产品组'] == '蒸烤微合计','汇总标准型号数'] += row['汇总标准型号数']
        productset_df.loc[productset_df['产品组'] == '蒸烤微合计','汇总核算价'] += row['汇总核算价']
    if row['产品组']  in productgroupset_map['灶集成']:
        productset_df.loc[productset_df['产品组'] == '灶集成','零售渠道标准型号数'] += row['零售渠道标准型号数']
        productset_df.loc[productset_df['产品组'] == '灶集成','零售渠道核算价'] += row['零售渠道核算价']
        productset_df.loc[productset_df['产品组'] == '灶集成','工程渠道标准型号数'] += row['工程渠道标准型号数']
        productset_df.loc[productset_df['产品组'] == '灶集成','工程渠道核算价'] += row['工程渠道核算价']
        productset_df.loc[productset_df['产品组'] == '灶集成','电商渠道标准型号数'] += row['电商渠道标准型号数']
        productset_df.loc[productset_df['产品组'] == '灶集成','电商渠道核算价'] += row['电商渠道核算价']
        productset_df.loc[productset_df['产品组'] == '灶集成','汇总标准型号数'] += row['汇总标准型号数']
        productset_df.loc[productset_df['产品组'] == '灶集成','汇总核算价'] += row['汇总核算价']
    if row['产品组']  in productgroupset_map['烹饪产品线合计']:
        productset_df.loc[productset_df['产品组'] == '烹饪产品线合计','零售渠道标准型号数'] += row['零售渠道标准型号数']
        productset_df.loc[productset_df['产品组'] == '烹饪产品线合计','零售渠道核算价'] += row['零售渠道核算价']
        productset_df.loc[productset_df['产品组'] == '烹饪产品线合计','工程渠道标准型号数'] += row['工程渠道标准型号数']
        productset_df.loc[productset_df['产品组'] == '烹饪产品线合计','工程渠道核算价'] += row['工程渠道核算价']
        productset_df.loc[productset_df['产品组'] == '烹饪产品线合计','电商渠道标准型号数'] += row['电商渠道标准型号数']
        productset_df.loc[productset_df['产品组'] == '烹饪产品线合计','电商渠道核算价'] += row['电商渠道核算价']
        productset_df.loc[productset_df['产品组'] == '烹饪产品线合计','汇总标准型号数'] += row['汇总标准型号数']
        productset_df.loc[productset_df['产品组'] == '烹饪产品线合计','汇总核算价'] += row['汇总核算价']
    if row['产品组']  in productgroupset_map['热水器两用炉合计']:
        productset_df.loc[productset_df['产品组'] == '热水器两用炉合计','零售渠道标准型号数'] += row['零售渠道标准型号数']
        productset_df.loc[productset_df['产品组'] == '热水器两用炉合计','零售渠道核算价'] += row['零售渠道核算价']
        productset_df.loc[productset_df['产品组'] == '热水器两用炉合计','工程渠道标准型号数'] += row['工程渠道标准型号数']
        productset_df.loc[productset_df['产品组'] == '热水器两用炉合计','工程渠道核算价'] += row['工程渠道核算价']
        productset_df.loc[productset_df['产品组'] == '热水器两用炉合计','电商渠道标准型号数'] += row['电商渠道标准型号数']
        productset_df.loc[productset_df['产品组'] == '热水器两用炉合计','电商渠道核算价'] += row['电商渠道核算价']
        productset_df.loc[productset_df['产品组'] == '热水器两用炉合计','汇总标准型号数'] += row['汇总标准型号数']
        productset_df.loc[productset_df['产品组'] == '热水器两用炉合计','汇总核算价'] += row['汇总核算价']
    if row['产品组']  in productgroupset_map['净热产品线合计']:
        productset_df.loc[productset_df['产品组'] == '净热产品线合计','零售渠道标准型号数'] += row['零售渠道标准型号数']
        productset_df.loc[productset_df['产品组'] == '净热产品线合计','零售渠道核算价'] += row['零售渠道核算价']
        productset_df.loc[productset_df['产品组'] == '净热产品线合计','工程渠道标准型号数'] += row['工程渠道标准型号数']
        productset_df.loc[productset_df['产品组'] == '净热产品线合计','工程渠道核算价'] += row['工程渠道核算价']
        productset_df.loc[productset_df['产品组'] == '净热产品线合计','电商渠道标准型号数'] += row['电商渠道标准型号数']
        productset_df.loc[productset_df['产品组'] == '净热产品线合计','电商渠道核算价'] += row['电商渠道核算价']
        productset_df.loc[productset_df['产品组'] == '净热产品线合计','汇总标准型号数'] += row['汇总标准型号数']
        productset_df.loc[productset_df['产品组'] == '净热产品线合计','汇总核算价'] += row['汇总核算价']
    if row['产品组']  in productgroupset_map['洗碗机产品线合计']:
        productset_df.loc[productset_df['产品组'] == '洗碗机产品线合计','零售渠道标准型号数'] += row['零售渠道标准型号数']
        productset_df.loc[productset_df['产品组'] == '洗碗机产品线合计','零售渠道核算价'] += row['零售渠道核算价']
        productset_df.loc[productset_df['产品组'] == '洗碗机产品线合计','工程渠道标准型号数'] += row['工程渠道标准型号数']
        productset_df.loc[productset_df['产品组'] == '洗碗机产品线合计','工程渠道核算价'] += row['工程渠道核算价']
        productset_df.loc[productset_df['产品组'] == '洗碗机产品线合计','电商渠道标准型号数'] += row['电商渠道标准型号数']
        productset_df.loc[productset_df['产品组'] == '洗碗机产品线合计','电商渠道核算价'] += row['电商渠道核算价']
        productset_df.loc[productset_df['产品组'] == '洗碗机产品线合计','汇总标准型号数'] += row['汇总标准型号数']
        productset_df.loc[productset_df['产品组'] == '洗碗机产品线合计','汇总核算价'] += row['汇总核算价']
    if row['产品组']  in productgroupset_map['国内合计']:
        productset_df.loc[productset_df['产品组'] == '国内合计','零售渠道标准型号数'] += row['零售渠道标准型号数']
        productset_df.loc[productset_df['产品组'] == '国内合计','零售渠道核算价'] += row['零售渠道核算价']
        productset_df.loc[productset_df['产品组'] == '国内合计','工程渠道标准型号数'] += row['工程渠道标准型号数']
        productset_df.loc[productset_df['产品组'] == '国内合计','工程渠道核算价'] += row['工程渠道核算价']
        productset_df.loc[productset_df['产品组'] == '国内合计','电商渠道标准型号数'] += row['电商渠道标准型号数']
        productset_df.loc[productset_df['产品组'] == '国内合计','电商渠道核算价'] += row['电商渠道核算价']
        productset_df.loc[productset_df['产品组'] == '国内合计','汇总标准型号数'] += row['汇总标准型号数']
        productset_df.loc[productset_df['产品组'] == '国内合计','汇总核算价'] += row['汇总核算价']
    
out_df2 = pd.concat([out_df1,productset_df]).reset_index(drop=True)
out_df2
all_productset_groups = pd.DataFrame({'产品组': productgroup_list2})
#将out_df1按照产品组列表的顺序进行排列
out_df2 = pd.merge(out_df2,all_productset_groups,on='产品组',how='right')
out_df2.to_excel('C:\\Users\\zhangbon\\Desktop\\单型号贡献-统计值.xlsx',index=False)

In [23]:
productset_df

,产品组,零售渠道标准型号数,零售渠道核算价,工程渠道标准型号数,工程渠道核算价,电商渠道标准型号数,电商渠道核算价,汇总标准型号数,汇总核算价
0,蒸烤微合计,48,776438748,37,69819382,58,114146235,87,1152961454
1,灶集成,26,565675440,9,30005790,14,884560,28,607476950
2,烹饪产品线合计,143,3205453354,105,581960856,128,673867201,220,5470508590
3,热水器两用炉合计,44,330155757,19,21386402,41,55323745,69,484111355
4,净热产品线合计,92,696983737,46,173009042,59,101478845,131,1126868975
5,洗碗机产品线合计,75,1130049845,58,471034155,54,208704675,135,2140406460
6,国内合计,406,9004166480,279,2176995253,305,2105372883,659,16372107831