In [230]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

### MAP关系汇总1、渠道对照 2、最终表格产品类别对应的产品组集合 3、产品组集合

In [231]:
# 物流的渠道对照关系清洗用
month = 202508
Channel_map = {
'工程': '工程',
'零售':'零售',
'电商不可售':'电商',
'电商':'电商',
'内部处理通用':'电商',
'借出渠道':'无',
'新品':'电商',
'战略电商':'电商',
'转出渠道':'无',
'每誉':'每誉',
'渠道':'无',
'海外':'海外',
'调出渠道':'无',
'非零售工程电商':'非零售工程电商',
'无':'无'
}
#用于合并计算
productgroupset_map = {
    '吸油烟机':['吸油烟机'],
    '灶具':['灶具'],
    '烤箱':['烤箱'],
    '蒸箱':['蒸箱'],
    '微波炉':['微波炉'],
    '蒸烤烹饪机':['蒸烤烹饪机'],
    '蒸烤微烹饪机':['蒸烤微烹饪机'],
    '蒸微':['蒸微'],
    '蒸烤微合计':['烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微'],
    '灶消烹饪机':['灶消烹饪机'],
    '灶蒸烹饪机':['灶蒸烹饪机'],
    '灶蒸烤烹饪机':['灶蒸烤烹饪机'],
    '灶烤烹饪机':['灶烤烹饪机'],
    '灶集成':['灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机'],
    '烹饪产品线合计':['灶具','烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微','灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机'],
    '消毒柜':['消毒柜'],
    '热水器':['热水器'],
    '两用炉':['两用炉'],
    '热水器两用炉合计':['热水器','两用炉'],
    '家用净水机':['家用净水机'],
    '商用净水机':['商用净水机'],
    '净热产品线合计':['热水器','两用炉','家用净水机','商用净水机'],
    '水槽洗碗机':['水槽洗碗机'],
    '嵌入式洗碗机':['嵌入式洗碗机'],
    '洗碗机产品线合计':['水槽洗碗机','嵌入式洗碗机'],
    '国内合计':['吸油烟机','灶具','烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微','灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机','消毒柜','热水器','两用炉','家用净水机','商用净水机','水槽洗碗机','嵌入式洗碗机'],
}
# 统计的产品组
productgroup_list = ['吸油烟机','灶具','烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微','灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机','消毒柜','热水器','两用炉','热水器两用炉合计','家用净水机','商用净水机','净热产品线合计','水槽洗碗机','嵌入式洗碗机','洗碗机产品线合计','国内合计']

### 获取物流体系的文件夹中的文件路劲和对应规则的sheetname。并将这些数据进行上写拼接（只保留了编码，渠道，发货数量）

In [232]:
#将这些excel的表格数据进行上下拼接，只要字段：商品编码、商品名称、渠道、实际出库数量
folder_path = fr"D:\000物料报表\{month}\单型号贡献-低效-长尾\物流发货1-8月"  # 请替换为实际的文件夹路径
excel_files = []
for root, dirs, files in os.walk(folder_path):
    for file in files:
        sheet_names = file[5:].replace(file[-5:],'')
        if (file.endswith('.xlsx') or file.endswith('.xls')) and not file.startswith('~$'):
            file_path = os.path.join(root, file)
            excel_files.append((file, sheet_names, file_path))
print(excel_files)

[('2025年1月明细.xlsx', '1月明细', 'D:\\000物料报表\\202508\\单型号贡献-低效-长尾\\物流发货1-8月\\2025年1月明细.xlsx'), ('2025年2月明细.xlsx', '2月明细', 'D:\\000物料报表\\202508\\单型号贡献-低效-长尾\\物流发货1-8月\\2025年2月明细.xlsx'), ('2025年3月明细.xlsx', '3月明细', 'D:\\000物料报表\\202508\\单型号贡献-低效-长尾\\物流发货1-8月\\2025年3月明细.xlsx'), ('2025年4月明细.xlsx', '4月明细', 'D:\\000物料报表\\202508\\单型号贡献-低效-长尾\\物流发货1-8月\\2025年4月明细.xlsx'), ('2025年5月明细.xlsx', '5月明细', 'D:\\000物料报表\\202508\\单型号贡献-低效-长尾\\物流发货1-8月\\2025年5月明细.xlsx'), ('2025年6月明细.xlsx', '6月明细', 'D:\\000物料报表\\202508\\单型号贡献-低效-长尾\\物流发货1-8月\\2025年6月明细.xlsx'), ('2025年7月明细.xlsx', '7月明细', 'D:\\000物料报表\\202508\\单型号贡献-低效-长尾\\物流发货1-8月\\2025年7月明细.xlsx'), ('2025年8月明细.xlsx', '8月明细', 'D:\\000物料报表\\202508\\单型号贡献-低效-长尾\\物流发货1-8月\\2025年8月明细.xlsx')]

In [233]:
#如果有报错请提示报错信息
df = pd.DataFrame()
for file in excel_files:
    try:
        df_temp = pd.read_excel(file[2], sheet_name=file[1])
        print(f'成功读取{file[0]}的{file[1]}表')
    except:
        print(f'读取{file[0]}的{file[1]}表失败')
    if '实际总数量' in df_temp.columns:
        df_temp = df_temp.rename(columns={'实际总数量':'实际出库数量'})
    df_temp = df_temp[['商品编码', '渠道', '实际出库数量']]
    df = pd.concat([df, df_temp], axis=0).reset_index(drop=True)
df = df.dropna(how='all').reset_index(drop=True)  # 仅当一行所有值都是NaN时才删除
df['商品编码'] = df['商品编码'].astype(str)
df
df['渠道'].value_counts()

成功读取2025年1月明细.xlsx的1月明细表
成功读取2025年2月明细.xlsx的2月明细表
成功读取2025年3月明细.xlsx的3月明细表
成功读取2025年4月明细.xlsx的4月明细表
成功读取2025年5月明细.xlsx的5月明细表
成功读取2025年6月明细.xlsx的6月明细表
成功读取2025年7月明细.xlsx的7月明细表
成功读取2025年8月明细.xlsx的8月明细表

渠道
零售        296394
工程         12725
电商不可售       6616
电商          3693
海外          1407
战略电商         129
每誉           113
新品            67
内部处理通用        15
借出渠道          14
渠道             4
调出渠道           2
转出渠道           2
米博新零售          1
商净             1
Name: count, dtype: int64

### 处理历史残留（财务的发货数据，将其转化为编码，名称，渠道，出库数量的形式）

In [234]:
#将这些excel的表格数据进行上下拼接，只要字段：商品编码、商品名称、渠道、实际出库数量
folder_path = fr"D:\000物料报表\{month}\单型号贡献-低效-长尾\财务9-12月"  # 请替换为实际的文件夹路径
excel_files = []
for root, dirs, files in os.walk(folder_path):
    for file in files:
        sheet_names = file[5:].replace(file[-5:],'')
        if (file.endswith('.xlsx') or file.endswith('.xls')) and not file.startswith('~$'):
            file_path = os.path.join(root, file)
            excel_files.append((file, sheet_names, file_path))
print(excel_files)

[('2024年10月明细.xlsx', '10月明细', 'D:\\000物料报表\\202508\\单型号贡献-低效-长尾\\财务9-12月\\2024年10月明细.xlsx'), ('2024年11月明细.xlsx', '11月明细', 'D:\\000物料报表\\202508\\单型号贡献-低效-长尾\\财务9-12月\\2024年11月明细.xlsx'), ('2024年12月明细.xlsx', '12月明细', 'D:\\000物料报表\\202508\\单型号贡献-低效-长尾\\财务9-12月\\2024年12月明细.xlsx'), ('2024年9月明细.xlsx', '9月明细', 'D:\\000物料报表\\202508\\单型号贡献-低效-长尾\\财务9-12月\\2024年9月明细.xlsx')]

In [235]:
caiwu_shouru = {'商品编码':[],'渠道':[],'实际出库数量':[]}
for file in excel_files:
    try:
        df_temp = pd.read_excel(file[2], sheet_name=file[1])
        print(f'成功读取{file[0]}的{file[1]}表')
    except:
        print(file[0], file[1])
    for index,row in df_temp.iterrows():
        if row['零售'] > 0:
            caiwu_shouru['商品编码'].append(row['物料编码'])
            caiwu_shouru['渠道'].append('零售')
            caiwu_shouru['实际出库数量'].append(row['零售'])
        if row['工程'] >0:
            caiwu_shouru['商品编码'].append(row['物料编码'])
            caiwu_shouru['渠道'].append('工程')
            caiwu_shouru['实际出库数量'].append(row['工程'])
        if row['电商'] >0:
            caiwu_shouru['商品编码'].append(row['物料编码'])
            caiwu_shouru['渠道'].append('电商')
            caiwu_shouru['实际出库数量'].append(row['电商'])
        if row['合计-发货'] - row['零售'] - row['工程'] - row['电商'] != 0:
            caiwu_shouru['商品编码'].append(row['物料编码'])
            caiwu_shouru['渠道'].append('非零售工程电商')
            caiwu_shouru['实际出库数量'].append(row['合计-发货'] - row['零售'] - row['工程'] - row['电商'])

df_caiwu = pd.DataFrame(caiwu_shouru)
df_caiwu['商品编码'] = df_caiwu['商品编码'].astype(str)
df_caiwu['渠道'].value_counts()
    #

成功读取2024年10月明细.xlsx的10月明细表
成功读取2024年11月明细.xlsx的11月明细表
成功读取2024年12月明细.xlsx的12月明细表
成功读取2024年9月明细.xlsx的9月明细表

渠道
零售         2060
电商         1789
工程          925
非零售工程电商      37
Name: count, dtype: int64

### 将财务和物流的数据进行拼接,并进行渠道清洗

In [236]:
df0 = pd.concat([df, df_caiwu], axis=0).reset_index(drop=True)
df0['商品编码'] = df0['商品编码'].astype(str)
df0['渠道'] = df0['渠道'].map(Channel_map).fillna('非零售工程电商')
df0 = df0[df0['渠道']!='无'].reset_index(drop=True)
df0['渠道'].value_counts()
# df0

渠道
零售         298454
工程          13650
电商          12309
海外           1407
每誉            113
非零售工程电商        39
Name: count, dtype: int64

### 将产品组信息、核算价匹配进去，计算各个渠道的统计值

In [237]:
# 复制df
df1 = df0.copy()
df1[['商品编码','渠道']] = df1[['商品编码','渠道']].astype(str)
df1[['实际出库数量']] = df1[['实际出库数量']].astype(float)

# PLM产品数据导入
df_product_group = pd.read_excel(fr"D:\000物料报表\{month}\单型号贡献-低效-长尾\产品生命周期状态全表20250703.xlsx")
df_product_group[['物料号','标准型号','国内/海外']] = df_product_group[['物料号','标准型号','国内/海外']].astype(str)
df_product_group = df_product_group[df_product_group['物料号'].str.len()>10]
df_product_group['物料号'] = df_product_group['物料号'].apply(lambda x: x[:13])
# df_product_group

In [238]:
#产品组对照关系
product_group_map = dict(zip(df_product_group['物料号'],df_product_group['产品组']))
#标准型号对照关系
product_standard = dict(zip(df_product_group['物料号'],df_product_group['标准型号']))
#记录国内/海外状态
product_country = dict(zip(df_product_group['物料号'],df_product_group['国内/海外']))

In [239]:
# 导入财务的核算价
df_price = pd.read_excel(fr"D:\000物料报表\{month}\单型号贡献-低效-长尾\核算价-20250901.xlsx")
df_price['产品编码'] = df_price['产品编码'].astype(str)
df_price['系统核算价'] = df_price['系统核算价'].astype(float)
# df_price
product_price_map = dict(zip(df_price['产品编码'],df_price['系统核算价']))

In [240]:

df1['产品组'] = df1['商品编码'].map(product_group_map)
df1['系统核算价'] = df1['商品编码'].map(product_price_map)
df1['核算价'] = df1['系统核算价'] * df1['实际出库数量']
df1['标准型号'] = df1['商品编码'].map(product_standard)
df1['国内/海外'] = df1['商品编码'].map(product_country)
df1 = df1[df1['商品编码'].str.startswith('10')].reset_index(drop=True)
df1

,商品编码,渠道,实际出库数量,产品组,系统核算价,核算价,标准型号,国内/海外
0,1009001100002,工程,1.0,蒸烤烹饪机,3550.0,3550.0,ZK50-01-F1.i,国内
1,1001002100022,工程,2.0,吸油烟机,1508.0,3016.0,JC03A,国内
2,1002003400032,工程,2.0,灶具,900.0,1800.0,TH3B,国内
3,1001002000018,工程,1.0,吸油烟机,3668.0,3668.0,03-X1A,国内
4,1003000500029,工程,1.0,消毒柜,1550.0,1550.0,ZTD100J-J31,国内
...,...,...,...,...,...,...,...,...
322374,1021000400003,非零售工程电商,240.0,地面手持式清洁机,4200.0,1008000.0,nan,国内
322375,1021000400007,非零售工程电商,810.0,地面手持式清洁机,3522.0,2852820.0,nan,国内
322376,1021000400008,非零售工程电商,150.0,地面手持式清洁机,3522.0,528300.0,QX-V8,国内
322377,1021000200003,非零售工程电商,300.0,地面手持式清洁机,3886.0,1165800.0,Q7Plus-L,国内
322378,1021000200004,非零售工程电商,400.0,地面手持式清洁机,4068.0,1627200.0,Q8,国内

In [241]:
df1['渠道'].value_counts()
# df1[df1['渠道']=='非零售工程电商']

渠道
零售         295587
工程          12957
电商          12277
海外           1407
每誉            112
非零售工程电商        39
Name: count, dtype: int64

### 这里导出的数据，只有整机有产品组的值，其他产品组为空,这个用于精简报告的分析

In [242]:
# 物流和财务的发货收入中是包含了1012开头的样机的，PLM中是只有成品的，所以这里样机的产品组是空的，样机不在我们报告的统计范围内
df1.to_excel(fr'D:\000物料报表\{month}\单物料产值\统计周期内产品核算价汇总.xlsx',index=False)

### 留下范围内的产品组(这样是会只剩下整机),只保留国内的渠道，并进行产品组和渠道分组聚合，这里要注意补充核算价！！！！！（在这里会输出一个文件用于后续低效和长尾的分析）

In [243]:
out_df = df1.copy()
out_df = out_df[out_df[r'国内/海外']=='国内']
out_df = out_df[out_df['产品组'].isin(productgroup_list)]
#这里要提示哪些数据的系统核算价是空的
print(f'没有系统核算价的是这些数据\n{out_df[out_df['系统核算价'].isnull()]['商品编码'].drop_duplicates()}')
print(len(out_df))

# 这里导出数据用于低效和长尾的分析。因为低效和长尾只看国内的成品情况（不包含样机，且在我们的统计产品组范围内）
out_df.to_excel(fr'D:\000物料报表\{month}\单型号贡献-低效-长尾\合并物流-财务-产品组-核算价-国内-用于低效-长尾.xlsx',index=False)
out_df

没有系统核算价的是这些数据
Series([], Name: 商品编码, dtype: object)
306178

,商品编码,渠道,实际出库数量,产品组,系统核算价,核算价,标准型号,国内/海外
0,1009001100002,工程,1.0,蒸烤烹饪机,3550.0,3550.0,ZK50-01-F1.i,国内
1,1001002100022,工程,2.0,吸油烟机,1508.0,3016.0,JC03A,国内
2,1002003400032,工程,2.0,灶具,900.0,1800.0,TH3B,国内
3,1001002000018,工程,1.0,吸油烟机,3668.0,3668.0,03-X1A,国内
4,1003000500029,工程,1.0,消毒柜,1550.0,1550.0,ZTD100J-J31,国内
...,...,...,...,...,...,...,...,...
322347,1013000600009,非零售工程电商,86.0,商用净水机,7980.0,686280.0,FZN400-02-A5,国内
322348,1013000100033,零售,40.0,家用净水机,2280.0,91200.0,YCZ-JT1800-01-M2E,国内
322349,1013000100033,电商,1.0,家用净水机,2280.0,2280.0,YCZ-JT1800-01-M2E,国内
322350,1013000100034,零售,44.0,家用净水机,2280.0,100320.0,YCZ-JT1800-01-M2E,国内
322351,1013000100034,非零售工程电商,10.0,家用净水机,2280.0,22800.0,YCZ-JT1800-01-M2E,国内

### 构建最终的统计结果表

In [255]:
df_calu = pd.DataFrame()
df_calu['产品类别'] = productgroupset_map.keys()
for k,v in productgroupset_map.items():
    # 零售渠道的统计
    vals = out_df[(out_df['产品组'].isin(v))&(out_df['渠道'] == '零售')]['标准型号'].nunique()
    df_calu.loc[df_calu['产品类别']==k,'零售渠道标准型号数'] = vals
    vals = out_df[(out_df['产品组'].isin(v))&(out_df['渠道'] == '零售')]['核算价'].sum()
    df_calu.loc[df_calu['产品类别']==k,'零售渠道核算价'] = vals

    # 工程渠道的统计
    vals = out_df[(out_df['产品组'].isin(v))&(out_df['渠道'] == '工程')]['标准型号'].nunique()
    df_calu.loc[df_calu['产品类别']==k,'工程渠道标准型号数'] = vals
    vals = out_df[(out_df['产品组'].isin(v))&(out_df['渠道'] == '工程')]['核算价'].sum()
    df_calu.loc[df_calu['产品类别']==k,'工程渠道核算价'] = vals

    # 电商渠道的统计
    vals = out_df[(out_df['产品组'].isin(v))&(out_df['渠道'] == '电商')]['标准型号'].nunique()
    df_calu.loc[df_calu['产品类别']==k,'电商渠道标准型号数'] = vals
    vals = out_df[(out_df['产品组'].isin(v))&(out_df['渠道'] == '电商')]['核算价'].sum()
    df_calu.loc[df_calu['产品类别']==k,'电商渠道核算价'] = vals

    # 合计
    vals = out_df[(out_df['产品组'].isin(v))]['标准型号'].nunique()
    df_calu.loc[df_calu['产品类别']==k,'汇总标准型号数'] = vals
    vals = out_df[(out_df['产品组'].isin(v))]['核算价'].sum()
    df_calu.loc[df_calu['产品类别']==k,'汇总核算价'] = vals
df_calu

,产品类别,零售渠道标准型号数,零售渠道核算价,工程渠道标准型号数,工程渠道核算价,电商渠道标准型号数,电商渠道核算价,汇总标准型号数,汇总核算价
0,吸油烟机,101.0,3.971926e+09,71.0,9.483131e+08,129.0,2.711788e+09,179.0,7.632027e+09
1,灶具,69.0,1.863339e+09,59.0,4.821357e+08,82.0,1.364595e+09,105.0,3.710070e+09
2,烤箱,9.0,5.911313e+07,7.0,3.595980e+06,13.0,1.336847e+07,14.0,7.607758e+07
3,蒸箱,8.0,7.105559e+07,5.0,3.386510e+06,14.0,1.683150e+07,15.0,9.127360e+07
4,微波炉,4.0,1.183224e+07,3.0,3.807290e+06,4.0,4.669440e+06,5.0,2.030897e+07
5,蒸烤烹饪机,25.0,6.267113e+08,19.0,5.746402e+07,44.0,2.179294e+08,47.0,9.021972e+08
6,蒸烤微烹饪机,2.0,7.726500e+06,3.0,1.565580e+06,6.0,5.381204e+07,6.0,6.310412e+07
7,蒸微,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.000000e+00
8,蒸烤微合计,48.0,7.764387e+08,37.0,6.981938e+07,81.0,3.066108e+08,87.0,1.152961e+09
9,灶消烹饪机,3.0,3.458743e+07,0.0,0.000000e+00,3.0,1.065590e+06,3.0,3.565302e+07
10,灶蒸烹饪机,1.0,5.782800e+05,0.0,0.000000e+00,2.0,7.196000e+04,2.0,6.502400e+05
11,灶蒸烤烹饪机,22.0,5.305097e+08,9.0,3.000579e+07,18.0,1.065817e+07,23.0,5.711737e+08
12,灶烤烹饪机,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.000000e+00
13,灶集成,26.0,5.656754e+08,9.0,3.000579e+07,23.0,1.179572e+07,28.0,6.074770e+08
14,烹饪产品线合计,143.0,3.205453e+09,105.0,5.819609e+08,186.0,1.683002e+09,220.0,5.470509e+09
15,消毒柜,22.0,1.709255e+08,16.0,1.500454e+08,22.0,1.048451e+08,29.0,4.258160e+08
16,热水器,39.0,3.244426e+08,18.0,2.137577e+07,55.0,1.323734e+08,63.0,4.781918e+08
17,两用炉,5.0,5.713122e+06,1.0,1.063200e+04,6.0,1.957760e+05,6.0,5.919530e+06
18,热水器两用炉合计,44.0,3.301558e+08,19.0,2.138640e+07,61.0,1.325692e+08,69.0,4.841114e+08
19,家用净水机,26.0,1.959024e+08,11.0,1.577220e+06,21.0,1.612870e+07,29.0,2.139068e+08
20,商用净水机,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.000000e+00,4.0,3.034840e+06
21,净热产品线合计,70.0,5.260582e+08,30.0,2.296362e+07,82.0,1.486979e+08,102.0,7.010530e+08
22,水槽洗碗机,44.0,4.961035e+08,26.0,9.324383e+07,52.0,1.324299e+08,69.0,7.330177e+08
23,嵌入式洗碗机,31.0,6.339463e+08,32.0,3.777903e+08,54.0,3.956521e+08,66.0,1.407389e+09
24,洗碗机产品线合计,75.0,1.130050e+09,58.0,4.710342e+08,106.0,5.280821e+08,135.0,2.140406e+09
25,国内合计,411.0,9.004413e+09,280.0,2.174317e+09,525.0,5.176415e+09,665.0,1.636981e+10

#### 输出结果

In [256]:

df_calu[['零售渠道核算价','电商渠道核算价','工程渠道核算价','汇总核算价']] = df_calu[['零售渠道核算价','电商渠道核算价','工程渠道核算价','汇总核算价']]/10000
df_calu['零售单型号贡献值'] = df_calu['零售渠道核算价']/df_calu['零售渠道标准型号数']
df_calu['工程单型号贡献值'] = df_calu['工程渠道核算价']/df_calu['工程渠道标准型号数']
df_calu['电商单型号贡献值'] = df_calu['电商渠道核算价']/df_calu['电商渠道标准型号数']
df_calu['汇总单型号贡献值'] = df_calu['汇总核算价']/df_calu['汇总标准型号数']
df_calu.to_excel(fr'D:\000物料报表\{month}\单型号贡献-低效-长尾\单型号贡献-统计值1.xlsx',index=False)
df_calu

,产品类别,零售渠道标准型号数,零售渠道核算价,工程渠道标准型号数,工程渠道核算价,电商渠道标准型号数,电商渠道核算价,汇总标准型号数,汇总核算价,零售单型号贡献值,工程单型号贡献值,电商单型号贡献值,汇总单型号贡献值
0,吸油烟机,101.0,397192.5998,71.0,94831.3064,129.0,271178.8338,179.0,7.632027e+05,3932.599998,1335.652203,2102.161502,4263.702458
1,灶具,69.0,186333.9166,59.0,48213.5684,82.0,136459.5336,105.0,3.710070e+05,2700.491545,817.179125,1664.140654,3533.400177
2,烤箱,9.0,5911.3130,7.0,359.5980,13.0,1336.8470,14.0,7.607758e+03,656.812556,51.371143,102.834385,543.411286
3,蒸箱,8.0,7105.5590,5.0,338.6510,14.0,1683.1500,15.0,9.127360e+03,888.194875,67.730200,120.225000,608.490667
4,微波炉,4.0,1183.2240,3.0,380.7290,4.0,466.9440,5.0,2.030897e+03,295.806000,126.909667,116.736000,406.179400
5,蒸烤烹饪机,25.0,62671.1288,19.0,5746.4022,44.0,21792.9374,47.0,9.021972e+04,2506.845152,302.442221,495.294032,1919.568477
6,蒸烤微烹饪机,2.0,772.6500,3.0,156.5580,6.0,5381.2040,6.0,6.310412e+03,386.325000,52.186000,896.867333,1051.735333
7,蒸微,0.0,0.0000,0.0,0.0000,0.0,0.0000,0.0,0.000000e+00,NaN,NaN,NaN,NaN
8,蒸烤微合计,48.0,77643.8748,37.0,6981.9382,81.0,30661.0824,87.0,1.152961e+05,1617.580725,188.701032,378.531881,1325.243051
9,灶消烹饪机,3.0,3458.7430,0.0,0.0000,3.0,106.5590,3.0,3.565302e+03,1152.914333,NaN,35.519667,1188.434000
10,灶蒸烹饪机,1.0,57.8280,0.0,0.0000,2.0,7.1960,2.0,6.502400e+01,57.828000,NaN,3.598000,32.512000
11,灶蒸烤烹饪机,22.0,53050.9730,9.0,3000.5790,18.0,1065.8170,23.0,5.711737e+04,2411.407864,333.397667,59.212056,2483.363870
12,灶烤烹饪机,0.0,0.0000,0.0,0.0000,0.0,0.0000,0.0,0.000000e+00,NaN,NaN,NaN,NaN
13,灶集成,26.0,56567.5440,9.0,3000.5790,23.0,1179.5720,28.0,6.074769e+04,2175.674769,333.397667,51.285739,2169.560536
14,烹饪产品线合计,143.0,320545.3354,105.0,58196.0856,186.0,168300.1880,220.0,5.470509e+05,2241.575772,554.248434,904.839720,2486.594814
15,消毒柜,22.0,17092.5540,16.0,15004.5420,22.0,10484.5060,29.0,4.258160e+04,776.934273,937.783875,476.568455,1468.331103
16,热水器,39.0,32444.2635,18.0,2137.5770,55.0,13237.3420,63.0,4.781918e+04,831.904192,118.754278,240.678945,759.034643
17,两用炉,5.0,571.3122,1.0,1.0632,6.0,19.5776,6.0,5.919530e+02,114.262440,1.063200,3.262933,98.658833
18,热水器两用炉合计,44.0,33015.5757,19.0,2138.6402,61.0,13256.9196,69.0,4.841114e+04,750.353993,112.560011,217.326551,701.610659
19,家用净水机,26.0,19590.2440,11.0,157.7220,21.0,1612.8700,29.0,2.139068e+04,753.470923,14.338364,76.803333,737.609517
20,商用净水机,0.0,0.0000,0.0,0.0000,0.0,0.0000,4.0,3.034840e+02,NaN,NaN,NaN,75.871000
21,净热产品线合计,70.0,52605.8197,30.0,2296.3622,82.0,14869.7896,102.0,7.010530e+04,751.511710,76.545407,181.338898,687.306819
22,水槽洗碗机,44.0,49610.3505,26.0,9324.3830,52.0,13242.9935,69.0,7.330177e+04,1127.507966,358.630115,254.672952,1062.344449
23,嵌入式洗碗机,31.0,63394.6340,32.0,37779.0325,54.0,39565.2125,66.0,1.407389e+05,2044.988194,1180.594766,732.689120,2132.407258
24,洗碗机产品线合计,75.0,113004.9845,58.0,47103.4155,106.0,52808.2060,135.0,2.140406e+05,1506.733127,812.127853,498.190623,1585.486267
25,国内合计,411.0,900441.2934,280.0,217431.7117,525.0,517641.5234,665.0,1.636981e+06,2190.854728,776.541828,985.983854,2461.625778