In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
### 所需要的所有文件：
# 物流的发货清单
# 财务的发货清单
# 核算价
# PLM的生命周期全表
### 输出的所有文件
# 统计周期内产品核算价汇总 用于物料精简报告，因为里面有国内国外
# 合并物流-财务-产品组-核算价-国内-用于低效-长尾  ，用于低效-长尾报告，里面只有国内
# 单型号贡献-统计值

### MAP关系汇总1、渠道对照 2、最终表格产品类别对应的产品组集合 3、产品组集合

In [2]:
# 物流的渠道对照关系清洗用
month = 202510
Channel_map = {
'工程': '工程',
'零售':'零售',
'电商不可售':'电商',
'电商':'电商',
'内部处理通用':'电商',
'借出渠道':'无',
'新品':'电商',
'战略电商':'电商',
'转出渠道':'无',
'每誉':'每誉',
'渠道':'无',
'海外':'海外',
'调出渠道':'无',
'非零售工程电商':'非零售工程电商',
'无':'无'
}
#用于合并计算
productgroupset_map = {
    '吸油烟机':['吸油烟机'],
    '灶具':['灶具'],
    '烤箱':['烤箱'],
    '蒸箱':['蒸箱'],
    '微波炉':['微波炉'],
    '蒸烤烹饪机':['蒸烤烹饪机'],
    '蒸烤微烹饪机':['蒸烤微烹饪机'],
    '蒸微':['蒸微'],
    '蒸烤微合计':['烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微'],
    '灶消烹饪机':['灶消烹饪机'],
    '灶蒸烹饪机':['灶蒸烹饪机'],
    '灶蒸烤烹饪机':['灶蒸烤烹饪机'],
    '灶烤烹饪机':['灶烤烹饪机'],
    '灶集成':['灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机'],
    '烹饪产品线合计':['灶具','烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微','灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机'],
    '消毒柜':['消毒柜'],
    '热水器':['热水器'],
    '两用炉':['两用炉'],
    '热水器两用炉合计':['热水器','两用炉'],
    '家用净水机':['家用净水机'],
    '商用净水机':['商用净水机'],
    '净热产品线合计':['热水器','两用炉','家用净水机','商用净水机'],
    '水槽洗碗机':['水槽洗碗机'],
    '嵌入式洗碗机':['嵌入式洗碗机'],
    '洗碗机产品线合计':['水槽洗碗机','嵌入式洗碗机'],
    '国内合计':['吸油烟机','灶具','烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微','灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机','消毒柜','热水器','两用炉','家用净水机','商用净水机','水槽洗碗机','嵌入式洗碗机'],
}
# 统计的产品组
productgroup_list = ['吸油烟机','灶具','烤箱','蒸箱','微波炉','蒸烤烹饪机','蒸烤微烹饪机','蒸微','灶消烹饪机','灶蒸烹饪机','灶蒸烤烹饪机','灶烤烹饪机','消毒柜','热水器','两用炉','热水器两用炉合计','家用净水机','商用净水机','净热产品线合计','水槽洗碗机','嵌入式洗碗机','洗碗机产品线合计','国内合计']

### 获取物流体系的文件夹中的文件路劲和对应规则的sheetname。并将这些数据进行上写拼接（只保留了编码，渠道，发货数量）

In [3]:
#将这些excel的表格数据进行上下拼接，只要字段：商品编码、商品名称、渠道、实际出库数量
folder_path = fr"D:\000物料报表\{month}\单型号贡献-低效-长尾\物流发货1-9月"  # 请替换为实际的文件夹路径
excel_files = []
for root, dirs, files in os.walk(folder_path):
    for file in files:
        sheet_names = file[5:].replace(file[-5:],'')
        if (file.endswith('.xlsx') or file.endswith('.xls')) and not file.startswith('~$'):
            file_path = os.path.join(root, file)
            excel_files.append((file, sheet_names, file_path))
print(excel_files)

[('2025年1月明细.xlsx', '1月明细', 'D:\\000物料报表\\202510\\单型号贡献-低效-长尾\\物流发货1-9月\\2025年1月明细.xlsx'), ('2025年2月明细.xlsx', '2月明细', 'D:\\000物料报表\\202510\\单型号贡献-低效-长尾\\物流发货1-9月\\2025年2月明细.xlsx'), ('2025年3月明细.xlsx', '3月明细', 'D:\\000物料报表\\202510\\单型号贡献-低效-长尾\\物流发货1-9月\\2025年3月明细.xlsx'), ('2025年4月明细.xlsx', '4月明细', 'D:\\000物料报表\\202510\\单型号贡献-低效-长尾\\物流发货1-9月\\2025年4月明细.xlsx'), ('2025年5月明细.xlsx', '5月明细', 'D:\\000物料报表\\202510\\单型号贡献-低效-长尾\\物流发货1-9月\\2025年5月明细.xlsx'), ('2025年6月明细.xlsx', '6月明细', 'D:\\000物料报表\\202510\\单型号贡献-低效-长尾\\物流发货1-9月\\2025年6月明细.xlsx'), ('2025年7月明细.xlsx', '7月明细', 'D:\\000物料报表\\202510\\单型号贡献-低效-长尾\\物流发货1-9月\\2025年7月明细.xlsx'), ('2025年8月明细.xlsx', '8月明细', 'D:\\000物料报表\\202510\\单型号贡献-低效-长尾\\物流发货1-9月\\2025年8月明细.xlsx'), ('2025年9月明细.xlsx', '9月明细', 'D:\\000物料报表\\202510\\单型号贡献-低效-长尾\\物流发货1-9月\\2025年9月明细.xlsx')]

In [4]:
#如果有报错请提示报错信息
df = pd.DataFrame()
for file in excel_files:
    try:
        df_temp = pd.read_excel(file[2], sheet_name=file[1])
        print(f'成功读取{file[0]}的{file[1]}表')
    except:
        print(f'读取{file[0]}的{file[1]}表失败')
    if '实际总数量' in df_temp.columns:
        df_temp = df_temp.rename(columns={'实际总数量':'实际出库数量'})
    df_temp = df_temp[['商品编码', '渠道', '实际出库数量']]
    df = pd.concat([df, df_temp], axis=0).reset_index(drop=True)
df = df.dropna(how='all').reset_index(drop=True)  # 仅当一行所有值都是NaN时才删除
df['商品编码'] = df['商品编码'].astype(str)
df['渠道'].value_counts()

成功读取2025年1月明细.xlsx的1月明细表
成功读取2025年2月明细.xlsx的2月明细表
成功读取2025年3月明细.xlsx的3月明细表
成功读取2025年4月明细.xlsx的4月明细表
成功读取2025年5月明细.xlsx的5月明细表
成功读取2025年6月明细.xlsx的6月明细表
成功读取2025年7月明细.xlsx的7月明细表
成功读取2025年8月明细.xlsx的8月明细表
成功读取2025年9月明细.xlsx的9月明细表

渠道
零售        345929
工程         14974
电商不可售       6616
电商          6011
海外          1702
战略电商         129
每誉           129
新品            67
内部处理通用        15
借出渠道          14
商净             5
渠道             4
调出渠道           2
转出渠道           2
米博新零售          1
Name: count, dtype: int64

In [6]:
df.to_excel(r"C:\Users\zhangbon\Desktop\2025发货.xlsx",index=False)

### 处理历史残留（财务的发货数据，将其转化为编码，名称，渠道，出库数量的形式）

In [21]:
#将这些excel的表格数据进行上下拼接，只要字段：商品编码、商品名称、渠道、实际出库数量
folder_path = fr"D:\000物料报表\{month}\单型号贡献-低效-长尾\财务10-12月"  # 请替换为实际的文件夹路径
excel_files = []
for root, dirs, files in os.walk(folder_path):
    for file in files:
        sheet_names = file[5:].replace(file[-5:],'')
        if (file.endswith('.xlsx') or file.endswith('.xls')) and not file.startswith('~$'):
            file_path = os.path.join(root, file)
            excel_files.append((file, sheet_names, file_path))
print(excel_files)

[('2024年10月明细.xlsx', '10月明细', 'D:\\000物料报表\\202510\\单型号贡献-低效-长尾\\财务10-12月\\2024年10月明细.xlsx'), ('2024年11月明细.xlsx', '11月明细', 'D:\\000物料报表\\202510\\单型号贡献-低效-长尾\\财务10-12月\\2024年11月明细.xlsx'), ('2024年12月明细.xlsx', '12月明细', 'D:\\000物料报表\\202510\\单型号贡献-低效-长尾\\财务10-12月\\2024年12月明细.xlsx')]

In [22]:
caiwu_shouru = {'商品编码':[],'渠道':[],'实际出库数量':[]}
for file in excel_files:
    try:
        df_temp = pd.read_excel(file[2], sheet_name=file[1])
        print(f'成功读取{file[0]}的{file[1]}表')
    except:
        print(file[0], file[1])
    for index,row in df_temp.iterrows():
        if row['零售'] > 0:
            caiwu_shouru['商品编码'].append(row['物料编码'])
            caiwu_shouru['渠道'].append('零售')
            caiwu_shouru['实际出库数量'].append(row['零售'])
        if row['工程'] >0:
            caiwu_shouru['商品编码'].append(row['物料编码'])
            caiwu_shouru['渠道'].append('工程')
            caiwu_shouru['实际出库数量'].append(row['工程'])
        if row['电商'] >0:
            caiwu_shouru['商品编码'].append(row['物料编码'])
            caiwu_shouru['渠道'].append('电商')
            caiwu_shouru['实际出库数量'].append(row['电商'])
        if row['合计-发货'] - row['零售'] - row['工程'] - row['电商'] != 0:
            caiwu_shouru['商品编码'].append(row['物料编码'])
            caiwu_shouru['渠道'].append('非零售工程电商')
            caiwu_shouru['实际出库数量'].append(row['合计-发货'] - row['零售'] - row['工程'] - row['电商'])

df_caiwu = pd.DataFrame(caiwu_shouru)
df_caiwu['商品编码'] = df_caiwu['商品编码'].astype(str)
df_caiwu['渠道'].value_counts()
    #

成功读取2024年10月明细.xlsx的10月明细表
成功读取2024年11月明细.xlsx的11月明细表
成功读取2024年12月明细.xlsx的12月明细表

渠道
零售         1541
电商         1368
工程          695
非零售工程电商      27
Name: count, dtype: int64

### 将财务和物流的数据进行拼接,并进行渠道清洗

In [23]:
df0 = pd.concat([df, df_caiwu], axis=0).reset_index(drop=True)
df0['商品编码'] = df0['商品编码'].astype(str)
df0['渠道'] = df0['渠道'].map(Channel_map).fillna('非零售工程电商')
df0 = df0[df0['渠道']!='无'].reset_index(drop=True)
df0['渠道'].value_counts()
# df0

渠道
零售         347470
工程          15669
电商          14206
海外           1702
每誉            129
非零售工程电商        33
Name: count, dtype: int64

### 将产品组信息、核算价匹配进去

In [24]:
# 复制df
df1 = df0.copy()
df1[['商品编码','渠道']] = df1[['商品编码','渠道']].astype(str)
df1[['实际出库数量']] = df1[['实际出库数量']].astype(float)

# PLM产品数据导入
df_product_group = pd.read_excel(fr"D:\000物料报表\{month}\单型号贡献-低效-长尾\产品生命周期状态全表.xlsx")
df_product_group[['物料号','标准型号','国内/海外']] = df_product_group[['物料号','标准型号','国内/海外']].astype(str)
df_product_group = df_product_group[df_product_group['物料号'].str.len()>10]
df_product_group['物料号'] = df_product_group['物料号'].apply(lambda x: x[:13])
# df_product_group

In [25]:
#产品组对照关系
product_group_map = dict(zip(df_product_group['物料号'],df_product_group['产品组']))
#标准型号对照关系
product_standard = dict(zip(df_product_group['物料号'],df_product_group['标准型号']))
#记录国内/海外状态
product_country = dict(zip(df_product_group['物料号'],df_product_group['国内/海外']))

In [26]:
# 导入财务的核算价
df_price = pd.read_excel(fr"D:\000物料报表\{month}\单型号贡献-低效-长尾\核算价-20250930.xlsx")
df_price['产品编码'] = df_price['产品编码'].astype(str)
df_price['系统核算价'] = df_price['系统核算价'].astype(float)
# df_price
product_price_map = dict(zip(df_price['产品编码'],df_price['系统核算价']))

In [27]:

df1['产品组'] = df1['商品编码'].map(product_group_map)
df1['系统核算价'] = df1['商品编码'].map(product_price_map)
df1['核算价'] = df1['系统核算价'] * df1['实际出库数量']
df1['标准型号'] = df1['商品编码'].map(product_standard)
df1['国内/海外'] = df1['商品编码'].map(product_country)
df1 = df1[df1['商品编码'].str.startswith('10')].reset_index(drop=True)
#这里要提示哪些数据的系统核算价是空的
print(f'国内没有系统核算价的是这些数据\n{df1[(df1['系统核算价'].isnull()&(df1['国内/海外']=='国内'))]['商品编码'].drop_duplicates()}')
print(len(df1))
df1

国内没有系统核算价的是这些数据
Series([], Name: 商品编码, dtype: object)
375015

,商品编码,渠道,实际出库数量,产品组,系统核算价,核算价,标准型号,国内/海外
0,1009001100002,工程,1.0,蒸烤烹饪机,3550.0,3550.0,ZK50-01-F1.i,国内
1,1001002100022,工程,2.0,吸油烟机,1508.0,3016.0,JC03A,国内
2,1002003400032,工程,2.0,灶具,900.0,1800.0,TH3B,国内
3,1001002000018,工程,1.0,吸油烟机,3668.0,3668.0,03-X1A,国内
4,1003000500029,工程,1.0,消毒柜,1550.0,1550.0,ZTD100J-J31,国内
...,...,...,...,...,...,...,...,...
375010,1021000400003,非零售工程电商,1866.0,地面手持式清洁机,4200.0,7837200.0,nan,国内
375011,1021000400006,非零售工程电商,1644.0,地面手持式清洁机,3346.0,5500824.0,QX-V7Plus,国内
375012,1021000400007,非零售工程电商,180.0,地面手持式清洁机,3522.0,633960.0,nan,国内
375013,1021000400008,非零售工程电商,2.0,地面手持式清洁机,3522.0,7044.0,QX-V8,国内
375014,1021000200004,非零售工程电商,90.0,地面手持式清洁机,4068.0,366120.0,Q8,国内

In [28]:
df1['渠道'].value_counts()
# df1[df1['渠道']=='非零售工程电商']

渠道
零售         344157
工程          14827
电商          14168
海外           1702
每誉            128
非零售工程电商        33
Name: count, dtype: int64

### 这里导出的数据，只有整机有产品组的值，其他产品组为空,这个用于精简报告的分析

In [29]:
# 物流和财务的发货收入中是包含了1012开头的样机的，PLM中是只有成品的，所以这里样机的产品组是空的，样机不在我们报告的统计范围内
# 这份导出的数据中是包含了国内国外的整机以及样机等数据，（样机等不会有产品组信息，因为PLM产品生命周期表中是没有样机的）
df1.to_excel(fr'D:\000物料报表\{month}\单物料产值\统计周期内产品核算价汇总.xlsx',index=False)

### 留下范围内的产品组(这样是会只剩下整机),只保留国内的渠道，这里要注意补充核算价！！！！！（在这里会输出一个文件用于后续低效和长尾的分析）

In [30]:
out_df = df1.copy()
out_df = out_df[out_df[r'国内/海外']=='国内']
out_df = out_df[out_df['产品组'].isin(productgroup_list)]
#这里要提示哪些数据的系统核算价是空的
print(f'没有系统核算价的是这些数据\n{out_df[out_df['系统核算价'].isnull()]['商品编码'].drop_duplicates()}')
print(len(out_df))

# 这里导出数据用于低效和长尾的分析。因为低效和长尾只看国内的成品情况（不包含样机，且在我们的统计产品组范围内）
out_df.to_excel(fr'D:\000物料报表\{month}\单型号贡献-低效-长尾\合并物流-财务-产品组-核算价-国内-用于低效-长尾.xlsx',index=False)
out_df

没有系统核算价的是这些数据
Series([], Name: 商品编码, dtype: object)
356495

,商品编码,渠道,实际出库数量,产品组,系统核算价,核算价,标准型号,国内/海外
0,1009001100002,工程,1.0,蒸烤烹饪机,3550.0,3550.0,ZK50-01-F1.i,国内
1,1001002100022,工程,2.0,吸油烟机,1508.0,3016.0,JC03A,国内
2,1002003400032,工程,2.0,灶具,900.0,1800.0,TH3B,国内
3,1001002000018,工程,1.0,吸油烟机,3668.0,3668.0,03-X1A,国内
4,1003000500029,工程,1.0,消毒柜,1550.0,1550.0,ZTD100J-J31,国内
...,...,...,...,...,...,...,...,...
374978,1013000500000,电商,7.0,家用净水机,3640.0,25480.0,YCZ-JT1800-HR7,国内
374979,1013000500001,零售,972.0,家用净水机,3720.0,3615840.0,YCZ-JT1800-HR7,国内
374980,1013000500001,工程,86.0,家用净水机,3720.0,319920.0,YCZ-JT1800-HR7,国内
374981,1013000100033,零售,61.0,家用净水机,2280.0,139080.0,YCZ-JT1800-01-M2E,国内
374982,1013000100034,零售,91.0,家用净水机,2280.0,207480.0,YCZ-JT1800-01-M2E,国内

### 构建最终的统计结果表

In [31]:
df_calu = pd.DataFrame()
df_calu['产品类别'] = productgroupset_map.keys()
for k,v in productgroupset_map.items():
    # 零售渠道的统计
    vals = out_df[(out_df['产品组'].isin(v))&(out_df['渠道'] == '零售')]['标准型号'].nunique()
    df_calu.loc[df_calu['产品类别']==k,'零售渠道标准型号数'] = vals
    vals = out_df[(out_df['产品组'].isin(v))&(out_df['渠道'] == '零售')]['核算价'].sum()
    df_calu.loc[df_calu['产品类别']==k,'零售渠道核算价'] = vals

    # 工程渠道的统计
    vals = out_df[(out_df['产品组'].isin(v))&(out_df['渠道'] == '工程')]['标准型号'].nunique()
    df_calu.loc[df_calu['产品类别']==k,'工程渠道标准型号数'] = vals
    vals = out_df[(out_df['产品组'].isin(v))&(out_df['渠道'] == '工程')]['核算价'].sum()
    df_calu.loc[df_calu['产品类别']==k,'工程渠道核算价'] = vals

    # 电商渠道的统计
    vals = out_df[(out_df['产品组'].isin(v))&(out_df['渠道'] == '电商')]['标准型号'].nunique()
    df_calu.loc[df_calu['产品类别']==k,'电商渠道标准型号数'] = vals
    vals = out_df[(out_df['产品组'].isin(v))&(out_df['渠道'] == '电商')]['核算价'].sum()
    df_calu.loc[df_calu['产品类别']==k,'电商渠道核算价'] = vals

    # 合计
    vals = out_df[(out_df['产品组'].isin(v))]['标准型号'].nunique()
    df_calu.loc[df_calu['产品类别']==k,'汇总标准型号数'] = vals
    vals = out_df[(out_df['产品组'].isin(v))]['核算价'].sum()
    df_calu.loc[df_calu['产品类别']==k,'汇总核算价'] = vals
df_calu

,产品类别,零售渠道标准型号数,零售渠道核算价,工程渠道标准型号数,工程渠道核算价,电商渠道标准型号数,电商渠道核算价,汇总标准型号数,汇总核算价
0,吸油烟机,94.0,4.111059e+09,71.0,9.264835e+08,131.0,2.608933e+09,172.0,7.646475e+09
1,灶具,66.0,1.902560e+09,60.0,4.690062e+08,88.0,1.340452e+09,108.0,3.712018e+09
2,烤箱,8.0,5.979212e+07,7.0,3.592640e+06,13.0,1.312160e+07,14.0,7.650636e+07
3,蒸箱,7.0,7.138789e+07,4.0,3.233750e+06,14.0,1.640138e+07,15.0,9.102302e+07
4,微波炉,4.0,1.218356e+07,3.0,3.817990e+06,4.0,4.916470e+06,5.0,2.091802e+07
5,蒸烤烹饪机,26.0,6.402838e+08,20.0,6.113453e+07,43.0,2.125358e+08,48.0,9.140467e+08
6,蒸烤微烹饪机,4.0,8.908920e+06,4.0,1.576500e+06,6.0,5.804663e+07,8.0,6.853205e+07
7,蒸微,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.000000e+00
8,蒸烤微合计,49.0,7.925563e+08,38.0,7.335541e+07,80.0,3.050219e+08,90.0,1.171026e+09
9,灶消烹饪机,3.0,3.574376e+07,0.0,0.000000e+00,3.0,1.217570e+06,3.0,3.696133e+07
10,灶蒸烹饪机,1.0,4.597800e+05,0.0,0.000000e+00,2.0,7.196000e+04,2.0,5.317400e+05
11,灶蒸烤烹饪机,21.0,5.545741e+08,12.0,2.791888e+07,18.0,1.342948e+07,24.0,5.959224e+08
12,灶烤烹饪机,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.000000e+00
13,灶集成,25.0,5.907776e+08,12.0,2.791888e+07,23.0,1.471901e+07,29.0,6.334155e+08
14,烹饪产品线合计,140.0,3.285894e+09,110.0,5.702805e+08,191.0,1.660193e+09,227.0,5.516459e+09
15,消毒柜,22.0,1.738095e+08,16.0,1.399328e+08,23.0,1.103833e+08,30.0,4.241255e+08
16,热水器,39.0,3.289172e+08,18.0,2.015193e+07,55.0,1.348688e+08,63.0,4.839379e+08
17,两用炉,5.0,5.754308e+06,1.0,1.063200e+04,6.0,1.885300e+05,6.0,5.953470e+06
18,热水器两用炉合计,44.0,3.346715e+08,19.0,2.016256e+07,61.0,1.350574e+08,69.0,4.898914e+08
19,家用净水机,25.0,2.016677e+08,12.0,1.656460e+06,24.0,1.594293e+07,29.0,2.194699e+08
20,商用净水机,0.0,0.000000e+00,0.0,0.000000e+00,0.0,0.000000e+00,5.0,3.381480e+06
21,净热产品线合计,69.0,5.363392e+08,31.0,2.181902e+07,85.0,1.510003e+08,103.0,7.127428e+08
22,水槽洗碗机,43.0,5.169778e+08,27.0,8.661152e+07,57.0,1.427654e+08,70.0,7.587451e+08
23,嵌入式洗碗机,33.0,6.614152e+08,32.0,4.057654e+08,58.0,3.906182e+08,68.0,1.457799e+09
24,洗碗机产品线合计,76.0,1.178393e+09,59.0,4.923769e+08,115.0,5.333836e+08,138.0,2.216544e+09
25,国内合计,401.0,9.285494e+09,287.0,2.150893e+09,545.0,5.063893e+09,670.0,1.651635e+10

#### 输出结果

In [32]:

df_calu[['零售渠道核算价','电商渠道核算价','工程渠道核算价','汇总核算价']] = df_calu[['零售渠道核算价','电商渠道核算价','工程渠道核算价','汇总核算价']]/10000
df_calu['零售单型号贡献值'] = df_calu['零售渠道核算价']/df_calu['零售渠道标准型号数']
df_calu['工程单型号贡献值'] = df_calu['工程渠道核算价']/df_calu['工程渠道标准型号数']
df_calu['电商单型号贡献值'] = df_calu['电商渠道核算价']/df_calu['电商渠道标准型号数']
df_calu['汇总单型号贡献值'] = df_calu['汇总核算价']/df_calu['汇总标准型号数']
df_calu.to_excel(fr'D:\000物料报表\{month}\单型号贡献-低效-长尾\单型号贡献-统计值.xlsx',index=False)
df_calu

,产品类别,零售渠道标准型号数,零售渠道核算价,工程渠道标准型号数,工程渠道核算价,电商渠道标准型号数,电商渠道核算价,汇总标准型号数,汇总核算价,零售单型号贡献值,工程单型号贡献值,电商单型号贡献值,汇总单型号贡献值
0,吸油烟机,94.0,411105.8886,71.0,92648.3456,131.0,260893.2968,172.0,7.646475e+05,4373.466900,1304.906276,1991.551884,4445.625180
1,灶具,66.0,190255.9670,60.0,46900.6248,88.0,134045.1806,108.0,3.712018e+05,2882.666167,781.677080,1523.240689,3437.053448
2,烤箱,8.0,5979.2120,7.0,359.2640,13.0,1312.1600,14.0,7.650636e+03,747.401500,51.323429,100.935385,546.474000
3,蒸箱,7.0,7138.7890,4.0,323.3750,14.0,1640.1380,15.0,9.102302e+03,1019.827000,80.843750,117.152714,606.820133
4,微波炉,4.0,1218.3560,3.0,381.7990,4.0,491.6470,5.0,2.091802e+03,304.589000,127.266333,122.911750,418.360400
5,蒸烤烹饪机,26.0,64028.3806,20.0,6113.4533,43.0,21253.5843,48.0,9.140467e+04,2462.630023,305.672665,494.269402,1904.263921
6,蒸烤微烹饪机,4.0,890.8920,4.0,157.6500,6.0,5804.6630,8.0,6.853205e+03,222.723000,39.412500,967.443833,856.650625
7,蒸微,0.0,0.0000,0.0,0.0000,0.0,0.0000,0.0,0.000000e+00,NaN,NaN,NaN,NaN
8,蒸烤微合计,49.0,79255.6296,38.0,7335.5413,80.0,30502.1923,90.0,1.171026e+05,1617.461829,193.040561,381.277404,1301.140147
9,灶消烹饪机,3.0,3574.3760,0.0,0.0000,3.0,121.7570,3.0,3.696133e+03,1191.458667,NaN,40.585667,1232.044333
10,灶蒸烹饪机,1.0,45.9780,0.0,0.0000,2.0,7.1960,2.0,5.317400e+01,45.978000,NaN,3.598000,26.587000
11,灶蒸烤烹饪机,21.0,55457.4090,12.0,2791.8880,18.0,1342.9480,24.0,5.959225e+04,2640.829000,232.657333,74.608222,2483.010208
12,灶烤烹饪机,0.0,0.0000,0.0,0.0000,0.0,0.0000,0.0,0.000000e+00,NaN,NaN,NaN,NaN
13,灶集成,25.0,59077.7630,12.0,2791.8880,23.0,1471.9010,29.0,6.334155e+04,2363.110520,232.657333,63.995696,2184.191448
14,烹饪产品线合计,140.0,328589.3596,110.0,57028.0541,191.0,166019.2739,227.0,5.516459e+05,2347.066854,518.436855,869.210858,2430.158315
15,消毒柜,22.0,17380.9470,16.0,13993.2750,23.0,11038.3290,30.0,4.241255e+04,790.043045,874.579687,479.927348,1413.751700
16,热水器,39.0,32891.7175,18.0,2015.1930,55.0,13486.8835,63.0,4.839379e+04,843.377372,111.955167,245.216064,768.155460
17,两用炉,5.0,575.4308,1.0,1.0632,6.0,18.8530,6.0,5.953470e+02,115.086160,1.063200,3.142167,99.224500
18,热水器两用炉合计,44.0,33467.1483,19.0,2016.2562,61.0,13505.7365,69.0,4.898914e+04,760.617007,106.118747,221.405516,709.987551
19,家用净水机,25.0,20166.7720,12.0,165.6460,24.0,1594.2930,29.0,2.194699e+04,806.670880,13.803833,66.428875,756.792793
20,商用净水机,0.0,0.0000,0.0,0.0000,0.0,0.0000,5.0,3.381480e+02,NaN,NaN,NaN,67.629600
21,净热产品线合计,69.0,53633.9203,31.0,2181.9022,85.0,15100.0295,103.0,7.127428e+04,777.303193,70.383942,177.647406,691.983301
22,水槽洗碗机,43.0,51697.7800,27.0,8661.1525,57.0,14276.5435,70.0,7.587451e+04,1202.273953,320.783426,250.465675,1083.921514
23,嵌入式洗碗机,33.0,66141.5175,32.0,40576.5410,58.0,39061.8185,68.0,1.457799e+05,2004.288409,1268.016906,673.479629,2143.821721
24,洗碗机产品线合计,76.0,117839.2975,59.0,49237.6935,115.0,53338.3620,138.0,2.216544e+05,1550.517072,834.537178,463.811843,1606.191181
25,国内合计,401.0,928549.4130,287.0,215089.2704,545.0,506389.2912,670.0,1.651635e+06,2315.584571,749.439967,929.154663,2465.126392